"""
config/paises.py — Catálogo de países TripOSINT
Campos por país:
  Obligatorios: region, emoji, capital, moneda_nombre, moneda_codigo,
                nivel_riesgo_maec (1-5)
  Meteo:        lat, lon, timezone
  Info:         idioma, enchufes, voltaje, frecuencia, internet_calidad,
                conduccion_lado, distancia_sistema
  Contactos:    telefono_emergencias, telefono_policia, telefono_embajada_es,
                url_maec
  Salud:        vacunas_recomendadas, vacunas_obligatorias, riesgo_salud,
                riesgo_malaria, notas_salud
  Cívico:       notas_civicas, requisitos_especiales, alertas_maec
  Prensa RSS:   fuentes_prensa [{nombre, url, idioma}]
"""

PAISES = {

    # ══════════════════════════════════════════════════════════════════════════
    # EUROPA
    # ══════════════════════════════════════════════════════════════════════════

    "Alemania": {
        "region": "Europa",
        "emoji": "🇩🇪",
        "capital": "Berlín",
        "moneda_nombre": "Euro",
        "moneda_codigo": "EUR",
        "nivel_riesgo_maec": 1,
        # Meteo
        "lat": 52.52, "lon": 13.405,
        "timezone": "Europe/Berlin",
        # Info
        "idioma": "Alemán",
        "idioma_oficial": "Alemán",
        "enchufes": "Tipo F (Schuko)",
        "voltaje": "230V",
        "frecuencia": "50Hz",
        "internet_calidad": "Excelente",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        # Contactos
        "telefono_emergencias": "112",
        "telefono_policia": "110",
        "telefono_embajada_es": "+49 30 254007-0",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/berlin/es/Paginas/inicio.aspx",
        # Entrada
        "visa_espana": "No requerida (Schengen)",
        "pasaporte_o_dni": "DNI válido",
        # Salud
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "Sistema sanitario de alta calidad. TARJETA SANITARIA EUROPEA válida.",
        # Cívico
        "notas_civicas": "Puntualidad muy valorada. Separación estricta de basura obligatoria. Silencio en domingos (Ruhezeit).",
        "requisitos_especiales": [],
        "alertas_maec": [],
        # Prensa
        "fuentes_prensa": [
            {"nombre": "Der Spiegel International", "url": "https://www.spiegel.de/international/index.rss", "idioma": "EN"},
            {"nombre": "DW Noticias", "url": "https://rss.dw.com/rdf/rss-es-all", "idioma": "ES"},
            {"nombre": "Deutsche Welle World", "url": "https://rss.dw.com/rdf/rss-en-top", "idioma": "EN"},
        ],
    },

    "Francia": {
        "region": "Europa",
        "emoji": "🇫🇷",
        "capital": "París",
        "moneda_nombre": "Euro",
        "moneda_codigo": "EUR",
        "nivel_riesgo_maec": 1,
        "lat": 48.8566, "lon": 2.3522,
        "timezone": "Europe/Paris",
        "idioma": "Francés",
        "idioma_oficial": "Francés",
        "enchufes": "Tipo E",
        "voltaje": "230V",
        "frecuencia": "50Hz",
        "internet_calidad": "Muy buena",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "112",
        "telefono_policia": "17",
        "telefono_embajada_es": "+33 1 44 43 18 00",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/paris/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (Schengen)",
        "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "TARJETA SANITARIA EUROPEA válida. Alta calidad asistencial.",
        "notas_civicas": "Saludo formal obligatorio en comercios (Bonjour/Bonsoir). Las propinas no son obligatorias pero se valoran.",
        "requisitos_especiales": [],
        "alertas_maec": ["Vigilancia elevada por amenaza terrorista (Plan Vigipirate)"],
        "fuentes_prensa": [
            {"nombre": "Le Monde", "url": "https://www.lemonde.fr/rss/une.xml", "idioma": "FR"},
            {"nombre": "France 24 ES", "url": "https://www.france24.com/es/rss", "idioma": "ES"},
            {"nombre": "RFI Español", "url": "https://www.rfi.fr/es/rss", "idioma": "ES"},
        ],
    },

    "Italia": {
        "region": "Europa",
        "emoji": "🇮🇹",
        "capital": "Roma",
        "moneda_nombre": "Euro",
        "moneda_codigo": "EUR",
        "nivel_riesgo_maec": 1,
        "lat": 41.9028, "lon": 12.4964,
        "timezone": "Europe/Rome",
        "idioma": "Italiano",
        "idioma_oficial": "Italiano",
        "enchufes": "Tipo F / Tipo L",
        "voltaje": "230V",
        "frecuencia": "50Hz",
        "internet_calidad": "Buena",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "112",
        "telefono_policia": "113",
        "telefono_embajada_es": "+39 06 6840401",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/roma/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (Schengen)",
        "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "TARJETA SANITARIA EUROPEA válida.",
        "notas_civicas": "Evitar entrada a iglesias sin hombros y rodillas cubiertos. Codice del Turista en ciudades históricas.",
        "requisitos_especiales": ["Algunas ciudades cobran tasa turística (1-6€/noche)"],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "ANSA News", "url": "https://www.ansa.it/sito/notizie/mondo/mondo_rss.xml", "idioma": "IT"},
            {"nombre": "La Repubblica", "url": "https://www.repubblica.it/rss/homepage/rss2.0.xml", "idioma": "IT"},
            {"nombre": "Corriere della Sera", "url": "https://xml2.corriereobjects.it/rss/homepage.xml", "idioma": "IT"},
        ],
    },

    "Reino Unido": {
        "region": "Europa",
        "emoji": "🇬🇧",
        "capital": "Londres",
        "moneda_nombre": "Libra esterlina",
        "moneda_codigo": "GBP",
        "nivel_riesgo_maec": 1,
        "lat": 51.5074, "lon": -0.1278,
        "timezone": "Europe/London",
        "idioma": "Inglés",
        "idioma_oficial": "Inglés",
        "enchufes": "Tipo G (3 patillas)",
        "voltaje": "230V",
        "frecuencia": "50Hz",
        "internet_calidad": "Excelente",
        "conduccion_lado": "Izquierda",
        "distancia_sistema": "Imperial (millas)",
        "telefono_emergencias": "999",
        "telefono_policia": "101 (no urgente)",
        "telefono_embajada_es": "+44 20 7235 5555",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/londres/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 6 meses, post-Brexit)",
        "pasaporte_o_dni": "Pasaporte (DNI no válido desde 2021)",
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "NHS disponible para emergencias. Recomendable seguro privado para no residentes.",
        "notas_civicas": "Hacer cola es norma social estricta. Propinas 10-15% en restaurantes. Conducción por la izquierda.",
        "requisitos_especiales": [
            "Pasaporte obligatorio (DNI no aceptado desde Brexit)",
            "Máximo 6 meses sin visado para turismo",
        ],
        "alertas_maec": ["Amenaza terrorista considerable (nivel SUBSTANTIAL)"],
        "fuentes_prensa": [
            {"nombre": "BBC News World", "url": "http://feeds.bbci.co.uk/news/world/rss.xml", "idioma": "EN"},
            {"nombre": "The Guardian World", "url": "https://www.theguardian.com/world/rss", "idioma": "EN"},
            {"nombre": "Reuters UK", "url": "https://feeds.reuters.com/reuters/UKdomesticNews", "idioma": "EN"},
        ],
    },

    "Turquía": {
        "region": "Europa",
        "emoji": "🇹🇷",
        "capital": "Ankara",
        "moneda_nombre": "Lira turca",
        "moneda_codigo": "TRY",
        "nivel_riesgo_maec": 2,
        "lat": 39.9334, "lon": 32.8597,
        "timezone": "Europe/Istanbul",
        "idioma": "Turco",
        "idioma_oficial": "Turco",
        "enchufes": "Tipo F (Schuko)",
        "voltaje": "230V",
        "frecuencia": "50Hz",
        "internet_calidad": "Buena (con restricciones)",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "112",
        "telefono_policia": "155",
        "telefono_embajada_es": "+90 312 440 35 60",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/ankara/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 90 días)",
        "pasaporte_o_dni": "Pasaporte o DNI",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea", "Hepatitis B"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado",
        "riesgo_malaria": "Muy bajo (zonas rurales sureste)",
        "notas_salud": "Agua del grifo no recomendada. Calor extremo en verano. Hospitales privados de buena calidad en ciudades.",
        "notas_civicas": "Respetar costumbres islámicas (Ramadán, mezquitas). Algunas redes sociales pueden estar restringidas.",
        "requisitos_especiales": ["Compra de lira turca solo en cambio oficial"],
        "alertas_maec": [
            "Precaución en zonas fronterizas con Siria e Irak",
            "Riesgo de atentados terroristas en zonas turísticas",
            "Restricciones en algunas redes sociales",
        ],
        "fuentes_prensa": [
            {"nombre": "Hurriyet Daily News", "url": "https://www.hurriyetdailynews.com/rss.aspx", "idioma": "EN"},
            {"nombre": "Daily Sabah", "url": "https://www.dailysabah.com/rss", "idioma": "EN"},
            {"nombre": "TRT World", "url": "https://www.trtworld.com/rss", "idioma": "EN"},
        ],
    },

    "Portugal": {
        "region": "Europa",
        "emoji": "🇵🇹",
        "capital": "Lisboa",
        "moneda_nombre": "Euro",
        "moneda_codigo": "EUR",
        "nivel_riesgo_maec": 1,
        "lat": 38.7223, "lon": -9.1393,
        "timezone": "Europe/Lisbon",
        "idioma": "Portugués",
        "idioma_oficial": "Portugués",
        "enchufes": "Tipo F (Schuko)",
        "voltaje": "230V",
        "frecuencia": "50Hz",
        "internet_calidad": "Muy buena",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "112",
        "telefono_policia": "112",
        "telefono_embajada_es": "+351 21 347 2381",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/lisboa/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (Schengen)",
        "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "TARJETA SANITARIA EUROPEA válida. Sistema sanitario de calidad.",
        "notas_civicas": "País muy seguro. Atención a carteristas en zonas turísticas de Lisboa y Oporto.",
        "requisitos_especiales": [],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "Público", "url": "https://feeds.feedburner.com/PublicoRSS", "idioma": "PT"},
            {"nombre": "Observador", "url": "https://observador.pt/feed/", "idioma": "PT"},
            {"nombre": "RTP Notícias", "url": "https://www.rtp.pt/noticias/rss", "idioma": "PT"},
        ],
    },

    "Grecia": {
        "region": "Europa",
        "emoji": "🇬🇷",
        "capital": "Atenas",
        "moneda_nombre": "Euro",
        "moneda_codigo": "EUR",
        "nivel_riesgo_maec": 1,
        "lat": 37.9838, "lon": 23.7275,
        "timezone": "Europe/Athens",
        "idioma": "Griego",
        "idioma_oficial": "Griego",
        "enchufes": "Tipo F (Schuko)",
        "voltaje": "230V",
        "frecuencia": "50Hz",
        "internet_calidad": "Buena",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "112",
        "telefono_policia": "100",
        "telefono_embajada_es": "+30 21 0345 6100",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/atenas/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (Schengen)",
        "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "TARJETA SANITARIA EUROPEA válida. Calor extremo en verano.",
        "notas_civicas": "Atención a estafas a turistas en Atenas. Respeto a lugares religiosos.",
        "requisitos_especiales": [],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "Ekathimerini", "url": "https://www.ekathimerini.com/rss/latest", "idioma": "EN"},
            {"nombre": "Greek Reporter", "url": "https://greekreporter.com/feed/", "idioma": "EN"},
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # AMÉRICA
    # ══════════════════════════════════════════════════════════════════════════

    "México": {
        "region": "América",
        "emoji": "🇲🇽",
        "capital": "Ciudad de México",
        "moneda_nombre": "Peso mexicano",
        "moneda_codigo": "MXN",
        "nivel_riesgo_maec": 3,
        "lat": 19.4326, "lon": -99.1332,
        "timezone": "America/Mexico_City",
        "idioma": "Español",
        "idioma_oficial": "Español",
        "enchufes": "Tipo A / Tipo B",
        "voltaje": "127V",
        "frecuencia": "60Hz",
        "internet_calidad": "Buena (ciudades)",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "911",
        "telefono_policia": "911",
        "telefono_embajada_es": "+52 55 5282 2974",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/mexico/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida",
        "pasaporte_o_dni": "Pasaporte (DNI no recomendado)",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea", "Rabia (zonas rurales)"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado",
        "riesgo_malaria": "Bajo (zonas rurales)",
        "notas_salud": "No beber agua del grifo. Precaución con comida callejera. Altitud en CDMX (2240m) puede causar mal de altura.",
        "notas_civicas": "Evitar zonas de alta criminalidad. No sacar el móvil en la calle. Usar taxis seguros (UBER recomendado).",
        "requisitos_especiales": [
            "Formulario de migración (puede ser digital)",
            "Seguro de viaje muy recomendable",
        ],
        "alertas_maec": [
            "Alta tasa de criminalidad en algunos estados (Guerrero, Michoacán, Tamaulipas)",
            "Evitar circular de noche en carreteras secundarias",
            "Riesgo de extorsión y secuestro exprés en zonas urbanas",
        ],
        "fuentes_prensa": [
            {"nombre": "El Universal", "url": "https://www.eluniversal.com.mx/rss.xml", "idioma": "ES"},
            {"nombre": "Proceso", "url": "https://www.proceso.com.mx/rss/noticias", "idioma": "ES"},
            {"nombre": "Animal Político", "url": "https://www.animalpolitico.com/feed", "idioma": "ES"},
        ],
    },

    "Colombia": {
        "region": "América",
        "emoji": "🇨🇴",
        "capital": "Bogotá",
        "moneda_nombre": "Peso colombiano",
        "moneda_codigo": "COP",
        "nivel_riesgo_maec": 3,
        "lat": 4.711, "lon": -74.0721,
        "timezone": "America/Bogota",
        "idioma": "Español",
        "idioma_oficial": "Español",
        "enchufes": "Tipo A / Tipo B",
        "voltaje": "110V",
        "frecuencia": "60Hz",
        "internet_calidad": "Buena (ciudades)",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "123",
        "telefono_policia": "112",
        "telefono_embajada_es": "+57 1 622 0090",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/bogota/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida",
        "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Fiebre amarilla", "Hepatitis A", "Tifoidea", "Rabia"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado",
        "riesgo_malaria": "Moderado (selva y costa)",
        "notas_salud": "Vacuna fiebre amarilla recomendada para zonas amazónicas. Altitud de Bogotá (2640m).",
        "notas_civicas": "Evitar zonas conflictivas. No mostrar joyas u objetos de valor en la calle.",
        "requisitos_especiales": ["Certificado fiebre amarilla si llega de zona endémica"],
        "alertas_maec": [
            "Zonas de conflicto armado (FARC disidentes, ELN)",
            "Alta criminalidad en algunas zonas urbanas",
            "Evitar departamentos: Chocó, Arauca, Norte de Santander frontera Venezuela",
        ],
        "fuentes_prensa": [
            {"nombre": "El Tiempo", "url": "https://www.eltiempo.com/rss/noticias.xml", "idioma": "ES"},
            {"nombre": "El Espectador", "url": "https://www.elespectador.com/feed/", "idioma": "ES"},
            {"nombre": "Semana", "url": "https://www.semana.com/rss-feed/", "idioma": "ES"},
        ],
    },

    "Argentina": {
        "region": "América",
        "emoji": "🇦🇷",
        "capital": "Buenos Aires",
        "moneda_nombre": "Peso argentino",
        "moneda_codigo": "ARS",
        "nivel_riesgo_maec": 2,
        "lat": -34.6037, "lon": -58.3816,
        "timezone": "America/Argentina/Buenos_Aires",
        "idioma": "Español",
        "idioma_oficial": "Español",
        "enchufes": "Tipo I (3 clavijas triangulares)",
        "voltaje": "220V",
        "frecuencia": "50Hz",
        "internet_calidad": "Buena",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "911",
        "telefono_policia": "101",
        "telefono_embajada_es": "+54 11 4819 2400",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/buenosaires/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida",
        "pasaporte_o_dni": "Pasaporte o DNI español",
        "vacunas_recomendadas": ["Hepatitis A"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "Alta calidad médica en Buenos Aires. Precaución con dengue en temporada.",
        "notas_civicas": "Situación económica compleja. Llevar dólares o euros para mejor tipo de cambio (dólar blue). Precaución con carteristas en BA.",
        "requisitos_especiales": ["Tipo de cambio oficial vs. informal — informarse bien"],
        "alertas_maec": [
            "Inestabilidad económica — planificar bien gastos",
            "Carteristas y robos en zona turística de Buenos Aires",
        ],
        "fuentes_prensa": [
            {"nombre": "La Nación", "url": "https://www.lanacion.com.ar/arc/outboundfeeds/rss/?outputType=xml", "idioma": "ES"},
            {"nombre": "Infobae", "url": "https://www.infobae.com/feeds/rss/", "idioma": "ES"},
            {"nombre": "Clarín", "url": "https://www.clarin.com/rss/lo-ultimo/", "idioma": "ES"},
        ],
    },

    "Estados Unidos": {
        "region": "América",
        "emoji": "🇺🇸",
        "capital": "Washington D.C.",
        "moneda_nombre": "Dólar estadounidense",
        "moneda_codigo": "USD",
        "nivel_riesgo_maec": 1,
        "lat": 38.9072, "lon": -77.0369,
        "timezone": "America/New_York",
        "idioma": "Inglés",
        "idioma_oficial": "Inglés",
        "enchufes": "Tipo A / Tipo B",
        "voltaje": "120V",
        "frecuencia": "60Hz",
        "internet_calidad": "Excelente",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Imperial (millas, pies)",
        "telefono_emergencias": "911",
        "telefono_policia": "911",
        "telefono_embajada_es": "+1 202 452 0100",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/washington/es/Paginas/inicio.aspx",
        "visa_espana": "ESTA obligatorio (Visa Waiver Program)",
        "pasaporte_o_dni": "Pasaporte (mínimo 6 meses validez)",
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "Seguro médico IMPRESCINDIBLE. Costes sanitarios muy elevados. Llevar medicación con receta.",
        "notas_civicas": "Propinas obligatorias (15-20%). Leyes varían por estado. Consumo alcohol prohibido en la calle en la mayoría de estados.",
        "requisitos_especiales": [
            "ESTA obligatoria — solicitar con mínimo 72h de antelación en esta.cbp.dhs.gov",
            "Seguro médico imprescindible",
            "Declaración aduanera al llegar",
        ],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "NPR News", "url": "https://feeds.npr.org/1001/rss.xml", "idioma": "EN"},
            {"nombre": "AP News", "url": "https://rsshub.app/apnews/topics/apf-topnews", "idioma": "EN"},
            {"nombre": "Reuters Top News", "url": "https://feeds.reuters.com/reuters/topNews", "idioma": "EN"},
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # ASIA
    # ══════════════════════════════════════════════════════════════════════════

    "Japón": {
        "region": "Asia",
        "emoji": "🇯🇵",
        "capital": "Tokio",
        "moneda_nombre": "Yen japonés",
        "moneda_codigo": "JPY",
        "nivel_riesgo_maec": 1,
        "lat": 35.6762, "lon": 139.6503,
        "timezone": "Asia/Tokyo",
        "idioma": "Japonés",
        "idioma_oficial": "Japonés",
        "enchufes": "Tipo A / Tipo B",
        "voltaje": "100V",
        "frecuencia": "50/60Hz",
        "internet_calidad": "Excelente",
        "conduccion_lado": "Izquierda",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "119 (ambulancia/bomberos)",
        "telefono_policia": "110",
        "telefono_embajada_es": "+81 3 3583 8531",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/tokio/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 90 días)",
        "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Encefalitis japonesa (zonas rurales)"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Muy bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "Sistema sanitario excelente. Barrera del idioma en hospitales. Llevar medicación propia (restricciones en algunos fármacos).",
        "notas_civicas": "No comer caminando. No hablar por teléfono en transporte público. No propinas (puede ofender). Separar residuos estrictamente.",
        "requisitos_especiales": [
            "Algunos medicamentos comunes en España están prohibidos (pseudoefedrina, codeína)",
            "Declaración aduanera al entrar",
        ],
        "alertas_maec": ["País sísmico — familiarizarse con protocolos de terremoto"],
        "fuentes_prensa": [
            {"nombre": "Japan Times", "url": "https://www.japantimes.co.jp/feed/", "idioma": "EN"},
            {"nombre": "NHK World", "url": "https://www3.nhk.or.jp/rss/news/cat0.xml", "idioma": "EN"},
            {"nombre": "Asahi Shimbun", "url": "https://www.asahi.com/rss/asahi/newsheadlines.rdf", "idioma": "EN"},
        ],
    },

    "India": {
        "region": "Asia",
        "emoji": "🇮🇳",
        "capital": "Nueva Delhi",
        "moneda_nombre": "Rupia india",
        "moneda_codigo": "INR",
        "nivel_riesgo_maec": 2,
        "lat": 28.6139, "lon": 77.2090,
        "timezone": "Asia/Kolkata",
        "idioma": "Hindi / Inglés",
        "idioma_oficial": "Hindi, Inglés",
        "enchufes": "Tipo C / Tipo D / Tipo M",
        "voltaje": "230V",
        "frecuencia": "50Hz",
        "internet_calidad": "Buena (ciudades)",
        "conduccion_lado": "Izquierda",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "112",
        "telefono_policia": "100",
        "telefono_embajada_es": "+91 11 4600 0870",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/nuevadelhi/es/Paginas/inicio.aspx",
        "visa_espana": "Requerida (e-Visa disponible online)",
        "pasaporte_o_dni": "Pasaporte (6 meses mínimo)",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea", "Rabia", "Encefalitis japonesa", "Hepatitis B"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Alto",
        "riesgo_malaria": "Moderado-Alto (zonas rurales y tropicales)",
        "notas_salud": "No beber agua del grifo. Cuidado con comida callejera. Golpe de calor en verano. Contaminación atmosférica grave en Delhi (octubre-marzo).",
        "notas_civicas": "Respetar costumbres religiosas (quitarse los zapatos). Regateo habitual en mercados. Fotografiar personas: pedir permiso.",
        "requisitos_especiales": [
            "e-Visa obligatoria — tramitar con 4 días de antelación",
            "Algunos destinos requieren Restricted Area Permit (RAP)",
        ],
        "alertas_maec": [
            "Zonas de tensión en Cachemira — evitar",
            "Precaución ante acoso a mujeres viajeras",
            "Alta contaminación en Delhi en invierno",
        ],
        "fuentes_prensa": [
            {"nombre": "The Hindu", "url": "https://www.thehindu.com/feeder/default.rss", "idioma": "EN"},
            {"nombre": "NDTV", "url": "https://feeds.feedburner.com/ndtvnews-top-stories", "idioma": "EN"},
            {"nombre": "Times of India", "url": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", "idioma": "EN"},
        ],
    },

    "Tailandia": {
        "region": "Asia",
        "emoji": "🇹🇭",
        "capital": "Bangkok",
        "moneda_nombre": "Baht tailandés",
        "moneda_codigo": "THB",
        "nivel_riesgo_maec": 2,
        "lat": 13.7563, "lon": 100.5018,
        "timezone": "Asia/Bangkok",
        "idioma": "Tailandés",
        "idioma_oficial": "Tailandés",
        "enchufes": "Tipo A / Tipo B / Tipo C",
        "voltaje": "220V",
        "frecuencia": "50Hz",
        "internet_calidad": "Muy buena",
        "conduccion_lado": "Izquierda",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "191",
        "telefono_policia": "191",
        "telefono_embajada_es": "+66 2 661 8284",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/bangkok/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 60 días)",
        "pasaporte_o_dni": "Pasaporte (6 meses mínimo)",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea", "Rabia", "Encefalitis japonesa"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado",
        "riesgo_malaria": "Bajo (fronteras Birmania/Camboya)",
        "notas_salud": "Dengue presente todo el año. No tocar monos (rabia). Hospitales privados de alta calidad.",
        "notas_civicas": "No insultar a la familia real (lèse-majesté, pena de prisión). Cubrir hombros y rodillas en templos. Quitar zapatos al entrar.",
        "requisitos_especiales": [
            "Lèse-majesté: hablar de la monarquía con extrema precaución",
            "Drogas: pena de muerte por tráfico",
        ],
        "alertas_maec": [
            "Inestabilidad política recurrente",
            "Precaución con scams a turistas (gemas, taxis)",
            "Zona sur frontera con Malasia: presencia de grupos armados",
        ],
        "fuentes_prensa": [
            {"nombre": "Bangkok Post", "url": "https://www.bangkokpost.com/rss/data/topstories.xml", "idioma": "EN"},
            {"nombre": "The Nation Thailand", "url": "https://www.nationthailand.com/rss.xml", "idioma": "EN"},
            {"nombre": "Khaosod English", "url": "https://www.khaosodenglish.com/feed/", "idioma": "EN"},
        ],
    },

    "China": {
        "region": "Asia",
        "emoji": "🇨🇳",
        "capital": "Pekín",
        "moneda_nombre": "Yuan renminbi",
        "moneda_codigo": "CNY",
        "nivel_riesgo_maec": 2,
        "lat": 39.9042, "lon": 116.4074,
        "timezone": "Asia/Shanghai",
        "idioma": "Chino mandarín",
        "idioma_oficial": "Chino mandarín",
        "enchufes": "Tipo A / Tipo C / Tipo I",
        "voltaje": "220V",
        "frecuencia": "50Hz",
        "internet_calidad": "Restringida (GFW)",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "120 (ambulancia)",
        "telefono_policia": "110",
        "telefono_embajada_es": "+86 10 6532 3629",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/pekin/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida hasta 30 días (exención temporal 2024)",
        "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Hepatitis A", "Hepatitis B", "Encefalitis japonesa"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado",
        "riesgo_malaria": "Muy bajo",
        "notas_salud": "Contaminación atmosférica (PM2.5) en ciudades industriales. Llevar mascarilla en días de polución.",
        "notas_civicas": "Internet restringida (Google, WhatsApp, Instagram bloqueados — instalar VPN antes de llegar). No fotografiar instalaciones militares.",
        "requisitos_especiales": [
            "VPN necesaria — instalar ANTES de llegar (luego no se puede descargar)",
            "Apps de pago: WeChat Pay o Alipay necesarias (difícil sin número chino)",
            "Registro obligatorio en hoteles (lo hace el hotel)",
        ],
        "alertas_maec": [
            "Restricciones en internet — preparar VPN con antelación",
            "Legislación sobre fotografías y seguridad muy estricta",
            "Tensión en Xinjiang y Tibet — restricciones de acceso",
        ],
        "fuentes_prensa": [
            {"nombre": "South China Morning Post", "url": "https://www.scmp.com/rss/91/feed", "idioma": "EN"},
            {"nombre": "Global Times", "url": "https://www.globaltimes.cn/rss/outbrain.xml", "idioma": "EN"},
            {"nombre": "Caixin Global", "url": "https://www.caixinglobal.com/rss/latest_news.xml", "idioma": "EN"},
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # ÁFRICA
    # ══════════════════════════════════════════════════════════════════════════

    "Marruecos": {
        "region": "África",
        "emoji": "🇲🇦",
        "capital": "Rabat",
        "moneda_nombre": "Dírham marroquí",
        "moneda_codigo": "MAD",
        "nivel_riesgo_maec": 2,
        "lat": 33.9716, "lon": -6.8498,
        "timezone": "Africa/Casablanca",
        "idioma": "Árabe / Francés / Amazigh",
        "idioma_oficial": "Árabe, Amazigh",
        "enchufes": "Tipo C / Tipo E",
        "voltaje": "220V",
        "frecuencia": "50Hz",
        "internet_calidad": "Buena (ciudades)",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "190 (policía) / 150 (ambulancia)",
        "telefono_policia": "190",
        "telefono_embajada_es": "+212 5 37 63 39 00",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/rabat/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 90 días)",
        "pasaporte_o_dni": "Pasaporte o DNI",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea", "Rabia (zonas rurales)"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "No beber agua del grifo. Precaución con comida en puestos callejeros.",
        "notas_civicas": "Respetar Ramadán (no comer/beber en público). Vestimenta modesta en medinas. Regateo esperado en zoco.",
        "requisitos_especiales": [],
        "alertas_maec": [
            "Precaución en zonas fronterizas con Argelia (cerradas)",
            "Atención a falsas guías y estafas a turistas en medinas",
        ],
        "fuentes_prensa": [
            {"nombre": "Le360 Maroc", "url": "https://fr.le360.ma/rss.xml", "idioma": "FR"},
            {"nombre": "Yabiladi", "url": "https://www.yabiladi.com/rss/news.xml", "idioma": "FR"},
            {"nombre": "Hespress", "url": "https://www.hespress.com/feed", "idioma": "AR"},
        ],
    },

    "Egipto": {
        "region": "África",
        "emoji": "🇪🇬",
        "capital": "El Cairo",
        "moneda_nombre": "Libra egipcia",
        "moneda_codigo": "EGP",
        "nivel_riesgo_maec": 3,
        "lat": 30.0444, "lon": 31.2357,
        "timezone": "Africa/Cairo",
        "idioma": "Árabe",
        "idioma_oficial": "Árabe",
        "enchufes": "Tipo C / Tipo F",
        "voltaje": "220V",
        "frecuencia": "50Hz",
        "internet_calidad": "Moderada",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "123 (ambulancia) / 122 (policía)",
        "telefono_policia": "122",
        "telefono_embajada_es": "+20 2 2735 6790",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/elcairo/es/Paginas/inicio.aspx",
        "visa_espana": "Requerida (e-Visa disponible)",
        "pasaporte_o_dni": "Pasaporte (6 meses mínimo)",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea", "Hepatitis B"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "No beber agua del grifo. Precaución con diarrea del viajero. Calor extremo.",
        "notas_civicas": "Vestimenta modesta especialmente para mujeres. Regateo en mercados. Propinas (baksheesh) muy extendidas.",
        "requisitos_especiales": ["e-Visa obligatoria — tramitar en evisa.gov.eg"],
        "alertas_maec": [
            "Riesgo terrorista en el Sinaí Norte — zona no recomendada",
            "Frontera con Libia y Sudán — evitar",
            "Manifestaciones y disturbios ocasionales",
        ],
        "fuentes_prensa": [
            {"nombre": "Al-Ahram English", "url": "https://english.ahram.org.eg/RSSFeed.aspx", "idioma": "EN"},
            {"nombre": "Egypt Independent", "url": "https://egyptindependent.com/feed/", "idioma": "EN"},
            {"nombre": "Mada Masr", "url": "https://www.madamasr.com/en/feed/", "idioma": "EN"},
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # OCEANÍA
    # ══════════════════════════════════════════════════════════════════════════

    "Australia": {
        "region": "Oceanía",
        "emoji": "🇦🇺",
        "capital": "Canberra",
        "moneda_nombre": "Dólar australiano",
        "moneda_codigo": "AUD",
        "nivel_riesgo_maec": 1,
        "lat": -35.2809, "lon": 149.1300,
        "timezone": "Australia/Sydney",
        "idioma": "Inglés",
        "idioma_oficial": "Inglés (de facto)",
        "enchufes": "Tipo I",
        "voltaje": "230V",
        "frecuencia": "50Hz",
        "internet_calidad": "Muy buena",
        "conduccion_lado": "Izquierda",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "000",
        "telefono_policia": "000",
        "telefono_embajada_es": "+61 2 6273 3555",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/canberra/es/Paginas/inicio.aspx",
        "visa_espana": "Requerida (eVisitor 651, gratuita online)",
        "pasaporte_o_dni": "Pasaporte (6 meses mínimo)",
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": ["Fiebre amarilla si llega de zona endémica"],
        "riesgo_salud": "Muy bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "Sistema sanitario excelente. Protección solar imprescindible (índice UV muy alto). Peligro fauna silvestre.",
        "notas_civicas": "País muy seguro. Respeto estricto a la naturaleza. Fumar muy restringido. Multas por cruzar en rojo.",
        "requisitos_especiales": [
            "eVisitor obligatoria — tramitar en immi.homeaffairs.gov.au",
            "Declaración de bioseguridad muy estricta — no introducir alimentos",
        ],
        "alertas_maec": [
            "Fauna peligrosa (serpientes, medusas, cocodrilos en el norte)",
            "Temporada de incendios (nov-mar) en zonas rurales",
            "UV extremo — protección solar imprescindible",
        ],
        "fuentes_prensa": [
            {"nombre": "ABC News Australia", "url": "https://www.abc.net.au/news/feed/51120/rss.xml", "idioma": "EN"},
            {"nombre": "The Sydney Morning Herald", "url": "https://www.smh.com.au/rss/feed.xml", "idioma": "EN"},
            {"nombre": "The Guardian Australia", "url": "https://www.theguardian.com/australia-news/rss", "idioma": "EN"},
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # EUROPA (ampliación)
    # ══════════════════════════════════════════════════════════════════════════

    "Austria": {
        "region": "Europa", "emoji": "🇦🇹", "capital": "Viena",
        "moneda_nombre": "Euro", "moneda_codigo": "EUR", "nivel_riesgo_maec": 1,
        "lat": 48.2082, "lon": 16.3738, "timezone": "Europe/Vienna",
        "idioma": "Alemán", "idioma_oficial": "Alemán",
        "enchufes": "Tipo F (Schuko)", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Excelente", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "112", "telefono_policia": "133",
        "telefono_embajada_es": "+43 1 505 57 88",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/viena/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (Schengen)", "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": [], "vacunas_obligatorias": [],
        "riesgo_salud": "Muy bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "TSE válida. Sistema sanitario excelente.",
        "notas_civicas": "Silencio dominical (Ruhezeit). Puntualidad muy valorada.",
        "requisitos_especiales": [], "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "Der Standard", "url": "https://www.derstandard.at/rss", "idioma": "DE"},
            {"nombre": "Austria Press Agency", "url": "https://www.apa.at/rss", "idioma": "DE"},
        ],
    },

    "Bélgica": {
        "region": "Europa", "emoji": "🇧🇪", "capital": "Bruselas",
        "moneda_nombre": "Euro", "moneda_codigo": "EUR", "nivel_riesgo_maec": 1,
        "lat": 50.8503, "lon": 4.3517, "timezone": "Europe/Brussels",
        "idioma": "Francés / Neerlandés / Alemán", "idioma_oficial": "Francés, Neerlandés, Alemán",
        "enchufes": "Tipo E", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Excelente", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "112", "telefono_policia": "101",
        "telefono_embajada_es": "+32 2 509 86 00",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/bruselas/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (Schengen)", "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": [], "vacunas_obligatorias": [],
        "riesgo_salud": "Muy bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "TSE válida.",
        "notas_civicas": "Sede de la UE y OTAN. Tres comunidades lingüísticas — sensibilidad al idioma.",
        "requisitos_especiales": [], "alertas_maec": ["Amenaza terrorista activa — nivel 2/4"],
        "fuentes_prensa": [
            {"nombre": "Le Soir", "url": "https://www.lesoir.be/rss.xml", "idioma": "FR"},
            {"nombre": "RTBF Info", "url": "https://www.rtbf.be/api/partner/json/rss?categories=14&partner=rss", "idioma": "FR"},
        ],
    },

    "Países Bajos": {
        "region": "Europa", "emoji": "🇳🇱", "capital": "Ámsterdam",
        "moneda_nombre": "Euro", "moneda_codigo": "EUR", "nivel_riesgo_maec": 1,
        "lat": 52.3676, "lon": 4.9041, "timezone": "Europe/Amsterdam",
        "idioma": "Neerlandés", "idioma_oficial": "Neerlandés",
        "enchufes": "Tipo F (Schuko)", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Excelente", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "112", "telefono_policia": "0900-8844",
        "telefono_embajada_es": "+31 70 302 4999",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/lahaya/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (Schengen)", "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": [], "vacunas_obligatorias": [],
        "riesgo_salud": "Muy bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "TSE válida.",
        "notas_civicas": "Cannabis tolerado en coffeeshops (no en la calle). Carril bici — respetar.",
        "requisitos_especiales": [], "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "NOS Nieuws", "url": "https://feeds.nos.nl/nosnieuwsalgemeen", "idioma": "NL"},
            {"nombre": "DutchNews.nl", "url": "https://www.dutchnews.nl/feed/", "idioma": "EN"},
        ],
    },

    "Suiza": {
        "region": "Europa", "emoji": "🇨🇭", "capital": "Berna",
        "moneda_nombre": "Franco suizo", "moneda_codigo": "CHF", "nivel_riesgo_maec": 1,
        "lat": 46.9480, "lon": 7.4474, "timezone": "Europe/Zurich",
        "idioma": "Alemán / Francés / Italiano / Romanche", "idioma_oficial": "Alemán, Francés, Italiano, Romanche",
        "enchufes": "Tipo J (único suizo)", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Excelente", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "112", "telefono_policia": "117",
        "telefono_embajada_es": "+41 31 350 52 52",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/berna/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (asociado Schengen)", "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": [], "vacunas_obligatorias": [],
        "riesgo_salud": "Muy bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "Sistema sanitario excelente. Seguro médico recomendable (caro).",
        "notas_civicas": "País muy ordenado. Silencio nocturno estricto. Precios muy elevados.",
        "requisitos_especiales": ["Vignette de autopista obligatoria (40 CHF/año)"],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "Swissinfo ES", "url": "https://www.swissinfo.ch/spa/rss/Es", "idioma": "ES"},
            {"nombre": "NZZ", "url": "https://www.nzz.ch/recent.rss", "idioma": "DE"},
        ],
    },

    "Polonia": {
        "region": "Europa", "emoji": "🇵🇱", "capital": "Varsovia",
        "moneda_nombre": "Esloti polaco", "moneda_codigo": "PLN", "nivel_riesgo_maec": 1,
        "lat": 52.2297, "lon": 21.0122, "timezone": "Europe/Warsaw",
        "idioma": "Polaco", "idioma_oficial": "Polaco",
        "enchufes": "Tipo E", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Muy buena", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "112", "telefono_policia": "997",
        "telefono_embajada_es": "+48 22 583 40 00",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/varsovia/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (Schengen)", "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": ["Encefalitis transmitida por garrapatas (zonas boscosas)"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "TSE válida.",
        "notas_civicas": "Cultura católica muy arraigada. Inviernos muy fríos.",
        "requisitos_especiales": [],
        "alertas_maec": ["Precaución zona norte frontera con Bielorrusia (Kaliningrado)"],
        "fuentes_prensa": [
            {"nombre": "Gazeta Wyborcza", "url": "https://wyborcza.pl/rss/feed.xml", "idioma": "PL"},
            {"nombre": "Notes from Poland", "url": "https://notesfrompoland.com/feed/", "idioma": "EN"},
        ],
    },

    "República Checa": {
        "region": "Europa", "emoji": "🇨🇿", "capital": "Praga",
        "moneda_nombre": "Corona checa", "moneda_codigo": "CZK", "nivel_riesgo_maec": 1,
        "lat": 50.0755, "lon": 14.4378, "timezone": "Europe/Prague",
        "idioma": "Checo", "idioma_oficial": "Checo",
        "enchufes": "Tipo E", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Muy buena", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "112", "telefono_policia": "158",
        "telefono_embajada_es": "+420 233 097 211",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/praga/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (Schengen)", "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": [], "vacunas_obligatorias": [],
        "riesgo_salud": "Muy bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "TSE válida.",
        "notas_civicas": "Atención a carteristas en el casco histórico de Praga. Taxis — usar apps.",
        "requisitos_especiales": [], "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "Prague Morning", "url": "https://www.praguemorning.cz/feed/", "idioma": "EN"},
            {"nombre": "Czech Radio", "url": "https://www.radio.cz/en/rss/full", "idioma": "EN"},
        ],
    },

    "Suecia": {
        "region": "Europa", "emoji": "🇸🇪", "capital": "Estocolmo",
        "moneda_nombre": "Corona sueca", "moneda_codigo": "SEK", "nivel_riesgo_maec": 1,
        "lat": 59.3293, "lon": 18.0686, "timezone": "Europe/Stockholm",
        "idioma": "Sueco", "idioma_oficial": "Sueco",
        "enchufes": "Tipo F (Schuko)", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Excelente", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "112", "telefono_policia": "114 14",
        "telefono_embajada_es": "+46 8 667 94 30",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/estocolmo/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (Schengen)", "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": [], "vacunas_obligatorias": [],
        "riesgo_salud": "Muy bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "TSE válida. Sistema sanitario excelente.",
        "notas_civicas": "Sociedad muy ordenada. Respeto al silencio en transporte público. Precios elevados.",
        "requisitos_especiales": [], "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "The Local Sweden", "url": "https://www.thelocal.se/feed.php", "idioma": "EN"},
            {"nombre": "SVT Nyheter", "url": "https://www.svt.se/nyheter/rss.xml", "idioma": "SV"},
        ],
    },

    "Noruega": {
        "region": "Europa", "emoji": "🇳🇴", "capital": "Oslo",
        "moneda_nombre": "Corona noruega", "moneda_codigo": "NOK", "nivel_riesgo_maec": 1,
        "lat": 59.9139, "lon": 10.7522, "timezone": "Europe/Oslo",
        "idioma": "Noruego", "idioma_oficial": "Noruego",
        "enchufes": "Tipo F (Schuko)", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Excelente", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "112", "telefono_policia": "02800",
        "telefono_embajada_es": "+47 22 92 28 00",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/oslo/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (asociado Schengen)", "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": [], "vacunas_obligatorias": [],
        "riesgo_salud": "Muy bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "Sistema sanitario excelente. TSE válida con acuerdo bilateral.",
        "notas_civicas": "País muy caro. Naturaleza: seguir normas de seguridad en senderismo.",
        "requisitos_especiales": [], "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "The Local Norway", "url": "https://www.thelocal.no/feed.php", "idioma": "EN"},
            {"nombre": "NRK Nyheter", "url": "https://www.nrk.no/nyheter/siste.rss", "idioma": "NO"},
        ],
    },

    "Dinamarca": {
        "region": "Europa", "emoji": "🇩🇰", "capital": "Copenhague",
        "moneda_nombre": "Corona danesa", "moneda_codigo": "DKK", "nivel_riesgo_maec": 1,
        "lat": 55.6761, "lon": 12.5683, "timezone": "Europe/Copenhagen",
        "idioma": "Danés", "idioma_oficial": "Danés",
        "enchufes": "Tipo K", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Excelente", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "112", "telefono_policia": "114",
        "telefono_embajada_es": "+45 35 42 47 00",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/copenhague/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (Schengen)", "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": [], "vacunas_obligatorias": [],
        "riesgo_salud": "Muy bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "TSE válida.",
        "notas_civicas": "Cultura ciclista muy desarrollada — respetar carriles bici. País muy caro.",
        "requisitos_especiales": [], "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "The Local Denmark", "url": "https://www.thelocal.dk/feed.php", "idioma": "EN"},
            {"nombre": "DR Nyheder", "url": "https://www.dr.dk/nyheder/service/feeds/allenyheder", "idioma": "DA"},
        ],
    },

    "Irlanda": {
        "region": "Europa", "emoji": "🇮🇪", "capital": "Dublín",
        "moneda_nombre": "Euro", "moneda_codigo": "EUR", "nivel_riesgo_maec": 1,
        "lat": 53.3498, "lon": -6.2603, "timezone": "Europe/Dublin",
        "idioma": "Inglés / Irlandés (gaélico)", "idioma_oficial": "Irlandés, Inglés",
        "enchufes": "Tipo G (3 patillas)", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Muy buena", "conduccion_lado": "Izquierda", "distancia_sistema": "Métrico",
        "telefono_emergencias": "112 / 999", "telefono_policia": "999",
        "telefono_embajada_es": "+353 1 269 1640",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/dublin/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (UE, no Schengen)", "pasaporte_o_dni": "Pasaporte recomendado",
        "vacunas_recomendadas": [], "vacunas_obligatorias": [],
        "riesgo_salud": "Muy bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "TSE válida.",
        "notas_civicas": "Conducción por la izquierda. Propinas 10-15%. Clima muy variable.",
        "requisitos_especiales": ["Irlanda NO es Schengen — frontera con RU: llevar pasaporte"],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "The Irish Times", "url": "https://www.irishtimes.com/cmlink/news-1.1319492", "idioma": "EN"},
            {"nombre": "RTÉ News", "url": "https://www.rte.ie/news/rss/news-headlines.xml", "idioma": "EN"},
        ],
    },

    "Croacia": {
        "region": "Europa", "emoji": "🇭🇷", "capital": "Zagreb",
        "moneda_nombre": "Euro", "moneda_codigo": "EUR", "nivel_riesgo_maec": 1,
        "lat": 45.8150, "lon": 15.9819, "timezone": "Europe/Zagreb",
        "idioma": "Croata", "idioma_oficial": "Croata",
        "enchufes": "Tipo F (Schuko)", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Buena", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "112", "telefono_policia": "192",
        "telefono_embajada_es": "+385 1 4896 444",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/zagreb/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (Schengen)", "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": [], "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "TSE válida.",
        "notas_civicas": "Costa dálmata muy turística en verano. Tráfico intenso en julio-agosto.",
        "requisitos_especiales": [], "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "Total Croatia News", "url": "https://www.total-croatia-news.com/feed", "idioma": "EN"},
            {"nombre": "HRT World Service", "url": "https://vijesti.hrt.hr/rss", "idioma": "HR"},
        ],
    },

    "Hungría": {
        "region": "Europa", "emoji": "🇭🇺", "capital": "Budapest",
        "moneda_nombre": "Forinto húngaro", "moneda_codigo": "HUF", "nivel_riesgo_maec": 1,
        "lat": 47.4979, "lon": 19.0402, "timezone": "Europe/Budapest",
        "idioma": "Húngaro", "idioma_oficial": "Húngaro",
        "enchufes": "Tipo F (Schuko)", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Muy buena", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "112", "telefono_policia": "107",
        "telefono_embajada_es": "+36 1 202 4006",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/budapest/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (Schengen)", "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": [], "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "TSE válida.",
        "notas_civicas": "Budapest — atención a estafas en bares (ruin bars). Idioma muy difícil.",
        "requisitos_especiales": [], "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "Hungary Today", "url": "https://hungarytoday.hu/feed/", "idioma": "EN"},
            {"nombre": "Daily News Hungary", "url": "https://dailynewshungary.com/feed/", "idioma": "EN"},
        ],
    },

    "Rumanía": {
        "region": "Europa", "emoji": "🇷🇴", "capital": "Bucarest",
        "moneda_nombre": "Leu rumano", "moneda_codigo": "RON", "nivel_riesgo_maec": 1,
        "lat": 44.4268, "lon": 26.1025, "timezone": "Europe/Bucharest",
        "idioma": "Rumano", "idioma_oficial": "Rumano",
        "enchufes": "Tipo F (Schuko)", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Muy buena", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "112", "telefono_policia": "112",
        "telefono_embajada_es": "+40 21 318 1065",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/bucarest/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (Schengen)", "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": ["Encefalitis transmitida por garrapatas (zonas rurales)"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "TSE válida.",
        "notas_civicas": "Carreteras en mal estado fuera de ciudades. Precaución con perros callejeros.",
        "requisitos_especiales": [], "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "Romania Insider", "url": "https://www.romania-insider.com/feed", "idioma": "EN"},
            {"nombre": "Digi24", "url": "https://www.digi24.ro/rss", "idioma": "RO"},
        ],
    },

    "Georgia": {
        "region": "Europa", "emoji": "🇬🇪", "capital": "Tiflis",
        "moneda_nombre": "Lari georgiano", "moneda_codigo": "GEL", "nivel_riesgo_maec": 2,
        "lat": 41.6938, "lon": 44.8015, "timezone": "Asia/Tbilisi",
        "idioma": "Georgiano", "idioma_oficial": "Georgiano",
        "enchufes": "Tipo C / Tipo F", "voltaje": "220V", "frecuencia": "50Hz",
        "internet_calidad": "Buena", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "112", "telefono_policia": "112",
        "telefono_embajada_es": "+995 32 229 39 95",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/ankara/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 365 días)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "Sistema sanitario limitado fuera de Tiflis.",
        "notas_civicas": "Hospitalidad muy marcada. Gastronomía excelente. Vino georgiano imprescindible.",
        "requisitos_especiales": [],
        "alertas_maec": ["Abjasia y Osetia del Sur — no acceder (territorios ocupados)"],
        "fuentes_prensa": [
            {"nombre": "Civil Georgia", "url": "https://civil.ge/feed", "idioma": "EN"},
            {"nombre": "Georgia Today", "url": "https://www.georgiatoday.ge/feed/", "idioma": "EN"},
        ],
    },

    "Ucrania": {
        "region": "Europa", "emoji": "🇺🇦", "capital": "Kiev",
        "moneda_nombre": "Grivna ucraniana", "moneda_codigo": "UAH", "nivel_riesgo_maec": 5,
        "lat": 50.4501, "lon": 30.5234, "timezone": "Europe/Kiev",
        "idioma": "Ucraniano", "idioma_oficial": "Ucraniano",
        "enchufes": "Tipo C / Tipo F", "voltaje": "220V", "frecuencia": "50Hz",
        "internet_calidad": "Variable (guerra)", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "112", "telefono_policia": "102",
        "telefono_embajada_es": "+380 44 490 6100",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/kiev/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": [], "vacunas_obligatorias": [],
        "riesgo_salud": "Muy alto (conflicto)", "riesgo_malaria": "Ninguno",
        "notas_salud": "Sistema sanitario gravemente afectado por la guerra.",
        "notas_civicas": "CONFLICTO ARMADO ACTIVO. No viajar bajo ningún concepto.",
        "requisitos_especiales": [],
        "alertas_maec": ["⛔ CONFLICTO ARMADO ACTIVO — Viaje totalmente desaconsejado"],
        "fuentes_prensa": [
            {"nombre": "Kyiv Independent", "url": "https://kyivindependent.com/feed/", "idioma": "EN"},
            {"nombre": "Ukraine World", "url": "https://ukraineworld.org/feed", "idioma": "EN"},
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # ORIENTE MEDIO
    # ══════════════════════════════════════════════════════════════════════════

    "Emiratos Árabes Unidos": {
        "region": "Oriente Medio", "emoji": "🇦🇪", "capital": "Abu Dabi",
        "moneda_nombre": "Dírham emiratí", "moneda_codigo": "AED", "nivel_riesgo_maec": 1,
        "lat": 24.4539, "lon": 54.3773, "timezone": "Asia/Dubai",
        "idioma": "Árabe", "idioma_oficial": "Árabe",
        "enchufes": "Tipo G (3 patillas)", "voltaje": "220V", "frecuencia": "50Hz",
        "internet_calidad": "Muy buena (con restricciones)", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "999", "telefono_policia": "999",
        "telefono_embajada_es": "+971 2 626 8544",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/abudhabi/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 90 días)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Hepatitis A", "Hepatitis B"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "Calor extremo (hasta 50°C en verano). Hidratación imprescindible.",
        "notas_civicas": "Vestimenta modesta en lugares públicos. Alcohol solo en hoteles. VoIP (WhatsApp calls) restringido. LGTBI+ ilegal.",
        "requisitos_especiales": [
            "Legislación muy estricta — respeto a costumbres islámicas",
            "Algunos medicamentos requieren autorización (opiáceos)",
        ],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "The National UAE", "url": "https://www.thenationalnews.com/rss", "idioma": "EN"},
            {"nombre": "Gulf News", "url": "https://gulfnews.com/rss", "idioma": "EN"},
        ],
    },

    "Arabia Saudí": {
        "region": "Oriente Medio", "emoji": "🇸🇦", "capital": "Riad",
        "moneda_nombre": "Riyal saudí", "moneda_codigo": "SAR", "nivel_riesgo_maec": 2,
        "lat": 24.6877, "lon": 46.7219, "timezone": "Asia/Riyadh",
        "idioma": "Árabe", "idioma_oficial": "Árabe",
        "enchufes": "Tipo G / Tipo A / Tipo B", "voltaje": "220V", "frecuencia": "60Hz",
        "internet_calidad": "Buena (con restricciones)", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "911", "telefono_policia": "999",
        "telefono_embajada_es": "+966 11 488 0707",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/riad/es/Paginas/inicio.aspx",
        "visa_espana": "Requerida (eVisa turística disponible)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Meningitis (obligatoria peregrinos)"],
        "vacunas_obligatorias": ["Meningitis ACWY (para Hajj/Umra)"],
        "riesgo_salud": "Bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "Calor extremo. Sistema sanitario bueno en ciudades.",
        "notas_civicas": "Alcohol prohibido. Vestimenta modesta obligatoria. LGTBI+ ilegal. No fotografiar personas sin permiso ni instalaciones gubernamentales.",
        "requisitos_especiales": ["eVisa turística — visita.visitsaudi.com"],
        "alertas_maec": ["Riesgo de ataques con drones/misiles desde Yemen en zona sur"],
        "fuentes_prensa": [
            {"nombre": "Arab News", "url": "https://www.arabnews.com/rss.xml", "idioma": "EN"},
            {"nombre": "Saudi Gazette", "url": "https://saudigazette.com.sa/feed/", "idioma": "EN"},
        ],
    },

    "Israel": {
        "region": "Oriente Medio", "emoji": "🇮🇱", "capital": "Jerusalén",
        "moneda_nombre": "Nuevo séquel", "moneda_codigo": "ILS", "nivel_riesgo_maec": 3,
        "lat": 31.7683, "lon": 35.2137, "timezone": "Asia/Jerusalem",
        "idioma": "Hebreo / Árabe", "idioma_oficial": "Hebreo",
        "enchufes": "Tipo H (único israelí) / Tipo C", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Excelente", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "101 (ambulancia) / 100 (policía)",
        "telefono_policia": "100",
        "telefono_embajada_es": "+972 3 510 1600",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/telaviv/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 90 días)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "Sistema sanitario excelente.",
        "notas_civicas": "Seguridad muy estricta en aeropuertos. Respetar Shabat (viernes noche-sábado). Zona de conflicto activo en Gaza y norte.",
        "requisitos_especiales": ["Controles de seguridad exhaustivos en aeropuertos"],
        "alertas_maec": [
            "Conflicto armado activo en Gaza — evitar totalmente",
            "Zona norte (frontera Líbano) — alta precaución",
            "Riesgo de cohetes y ataques en cualquier zona",
        ],
        "fuentes_prensa": [
            {"nombre": "Haaretz English", "url": "https://www.haaretz.com/rss", "idioma": "EN"},
            {"nombre": "The Times of Israel", "url": "https://www.timesofisrael.com/feed/", "idioma": "EN"},
        ],
    },

    "Jordania": {
        "region": "Oriente Medio", "emoji": "🇯🇴", "capital": "Amán",
        "moneda_nombre": "Dinar jordano", "moneda_codigo": "JOD", "nivel_riesgo_maec": 2,
        "lat": 31.9539, "lon": 35.9106, "timezone": "Asia/Amman",
        "idioma": "Árabe", "idioma_oficial": "Árabe",
        "enchufes": "Tipo B / Tipo C / Tipo D / Tipo F / Tipo G", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Buena", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "911", "telefono_policia": "191",
        "telefono_embajada_es": "+962 6 590 6400",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/amman/es/Paginas/inicio.aspx",
        "visa_espana": "Requerida (Jordan Pass o visa on arrival)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo-Moderado", "riesgo_malaria": "Ninguno",
        "notas_salud": "No beber agua del grifo. Calor extremo en verano.",
        "notas_civicas": "País relativamente liberal para la región. Petra y Wadi Rum — visitar con guía.",
        "requisitos_especiales": ["Jordan Pass incluye visa + entrada a Petra"],
        "alertas_maec": ["Precaución en frontera norte con Siria e Irak"],
        "fuentes_prensa": [
            {"nombre": "Jordan Times", "url": "https://www.jordantimes.com/rss.xml", "idioma": "EN"},
            {"nombre": "Roya News", "url": "https://en.roya.news/rss.xml", "idioma": "EN"},
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # ASIA (ampliación)
    # ══════════════════════════════════════════════════════════════════════════

    "Corea del Sur": {
        "region": "Asia", "emoji": "🇰🇷", "capital": "Seúl",
        "moneda_nombre": "Won surcoreano", "moneda_codigo": "KRW", "nivel_riesgo_maec": 1,
        "lat": 37.5665, "lon": 126.9780, "timezone": "Asia/Seoul",
        "idioma": "Coreano", "idioma_oficial": "Coreano",
        "enchufes": "Tipo C / Tipo F", "voltaje": "220V", "frecuencia": "60Hz",
        "internet_calidad": "Excelente (la más rápida del mundo)", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "119 (bomberos/ambulancia)", "telefono_policia": "112",
        "telefono_embajada_es": "+82 2 794 3581",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/seul/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 90 días)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Encefalitis japonesa (zonas rurales)"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Muy bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "Sistema sanitario excelente. Barrera del idioma en hospitales.",
        "notas_civicas": "Jerarquía social muy marcada. Comida picante — avisar de intolerancias. K-culture muy visible.",
        "requisitos_especiales": ["K-ETA puede ser requerida — verificar en kentravel.com"],
        "alertas_maec": ["Tensión con Corea del Norte — seguir instrucciones autoridades en caso de alerta"],
        "fuentes_prensa": [
            {"nombre": "Korea Herald", "url": "https://www.koreaherald.com/rss/rss_01.xml", "idioma": "EN"},
            {"nombre": "Korea Times", "url": "https://www.koreatimes.co.kr/www/rss/rss.xml", "idioma": "EN"},
        ],
    },

    "Singapur": {
        "region": "Asia", "emoji": "🇸🇬", "capital": "Singapur",
        "moneda_nombre": "Dólar de Singapur", "moneda_codigo": "SGD", "nivel_riesgo_maec": 1,
        "lat": 1.3521, "lon": 103.8198, "timezone": "Asia/Singapore",
        "idioma": "Inglés / Chino / Malayo / Tamil", "idioma_oficial": "Inglés, Chino, Malayo, Tamil",
        "enchufes": "Tipo G (3 patillas)", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Excelente", "conduccion_lado": "Izquierda", "distancia_sistema": "Métrico",
        "telefono_emergencias": "995 (ambulancia)", "telefono_policia": "999",
        "telefono_embajada_es": "+65 6732 9788",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/singapur/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 30 días)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Hepatitis A", "Hepatitis B"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Muy bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "Sistema sanitario de clase mundial. Dengue presente — protección mosquitos.",
        "notas_civicas": "Multas severas: chicle, cruzar en rojo, comer en metro. Drogas: pena de muerte. Muy limpio y ordenado.",
        "requisitos_especiales": ["Pena de muerte por tráfico de drogas — incluso tránsito"],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "The Straits Times", "url": "https://www.straitstimes.com/global-nav/rss", "idioma": "EN"},
            {"nombre": "Channel NewsAsia", "url": "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml", "idioma": "EN"},
        ],
    },

    "Vietnam": {
        "region": "Asia", "emoji": "🇻🇳", "capital": "Hanói",
        "moneda_nombre": "Dong vietnamita", "moneda_codigo": "VND", "nivel_riesgo_maec": 2,
        "lat": 21.0285, "lon": 105.8542, "timezone": "Asia/Ho_Chi_Minh",
        "idioma": "Vietnamita", "idioma_oficial": "Vietnamita",
        "enchufes": "Tipo A / Tipo C / Tipo F", "voltaje": "220V", "frecuencia": "50Hz",
        "internet_calidad": "Buena", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "115 (ambulancia)", "telefono_policia": "113",
        "telefono_embajada_es": "+84 24 3771 5207",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/hanoi/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 45 días)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea", "Rabia", "Encefalitis japonesa"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado", "riesgo_malaria": "Bajo (zonas rurales)",
        "notas_salud": "No beber agua del grifo. Tráfico caótico — precaución al cruzar. Dengue presente.",
        "notas_civicas": "Regateo habitual. No fotografiar instalaciones militares ni policiales. Sensibilidad política.",
        "requisitos_especiales": [],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "VnExpress International", "url": "https://e.vnexpress.net/rss/news.rss", "idioma": "EN"},
            {"nombre": "Vietnam News", "url": "https://vietnamnews.vn/rss/home.rss", "idioma": "EN"},
        ],
    },

    "Indonesia": {
        "region": "Asia", "emoji": "🇮🇩", "capital": "Yakarta",
        "moneda_nombre": "Rupia indonesia", "moneda_codigo": "IDR", "nivel_riesgo_maec": 2,
        "lat": -6.2088, "lon": 106.8456, "timezone": "Asia/Jakarta",
        "idioma": "Indonesio (Bahasa)", "idioma_oficial": "Bahasa Indonesia",
        "enchufes": "Tipo C / Tipo F", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Buena (ciudades)", "conduccion_lado": "Izquierda", "distancia_sistema": "Métrico",
        "telefono_emergencias": "119 (ambulancia)", "telefono_policia": "110",
        "telefono_embajada_es": "+62 21 3143 355",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/yakarta/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida Bali/aeropuertos principales (30 días)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea", "Rabia", "Encefalitis japonesa"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado", "riesgo_malaria": "Moderado (islas orientales)",
        "notas_salud": "Dengue presente todo el año. Rabia en Bali — no tocar animales. No beber agua del grifo.",
        "notas_civicas": "País mayoritariamente musulmán — vestimenta modesta fuera de zonas turísticas. Respetar templos hindúes en Bali.",
        "requisitos_especiales": ["Bali: pena de muerte por tráfico de drogas"],
        "alertas_maec": [
            "Riesgo terrorista — grupos yihadistas activos",
            "Zona sísmica y volcánica — seguir alertas locales",
        ],
        "fuentes_prensa": [
            {"nombre": "Jakarta Post", "url": "https://www.thejakartapost.com/feed", "idioma": "EN"},
            {"nombre": "Kompas English", "url": "https://www.kompas.com/rss", "idioma": "EN"},
        ],
    },

    "Malasia": {
        "region": "Asia", "emoji": "🇲🇾", "capital": "Kuala Lumpur",
        "moneda_nombre": "Ringgit malayo", "moneda_codigo": "MYR", "nivel_riesgo_maec": 2,
        "lat": 3.1390, "lon": 101.6869, "timezone": "Asia/Kuala_Lumpur",
        "idioma": "Malayo", "idioma_oficial": "Malayo",
        "enchufes": "Tipo G (3 patillas)", "voltaje": "240V", "frecuencia": "50Hz",
        "internet_calidad": "Muy buena", "conduccion_lado": "Izquierda", "distancia_sistema": "Métrico",
        "telefono_emergencias": "999", "telefono_policia": "999",
        "telefono_embajada_es": "+60 3 2148 4686",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/kualalumpur/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 90 días)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea", "Rabia"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado", "riesgo_malaria": "Bajo (zonas boscosas Borneo)",
        "notas_salud": "Dengue presente. No beber agua del grifo en zonas rurales.",
        "notas_civicas": "País multicultural. Respeto a vestimenta en mezquitas. Pena de muerte por drogas.",
        "requisitos_especiales": ["Pena de muerte por tráfico de drogas"],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "Malaysiakini", "url": "https://www.malaysiakini.com/rss", "idioma": "EN"},
            {"nombre": "The Star Malaysia", "url": "https://www.thestar.com.my/rss/News/Nation/", "idioma": "EN"},
        ],
    },

    "Nepal": {
        "region": "Asia", "emoji": "🇳🇵", "capital": "Katmandú",
        "moneda_nombre": "Rupia nepalesa", "moneda_codigo": "NPR", "nivel_riesgo_maec": 2,
        "lat": 27.7172, "lon": 85.3240, "timezone": "Asia/Kathmandu",
        "idioma": "Nepalés", "idioma_oficial": "Nepalés",
        "enchufes": "Tipo C / Tipo D / Tipo M", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Moderada", "conduccion_lado": "Izquierda", "distancia_sistema": "Métrico",
        "telefono_emergencias": "102 (ambulancia)", "telefono_policia": "100",
        "telefono_embajada_es": "+977 1 443 5938",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/nuevadelhi/es/Paginas/inicio.aspx",
        "visa_espana": "Requerida (on arrival o e-Visa)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea", "Rabia", "Encefalitis japonesa"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado", "riesgo_malaria": "Bajo (Terai, <2000m)",
        "notas_salud": "Mal de altura — ascenso gradual imprescindible. No beber agua sin tratar. Llevar botiquín completo para trekking.",
        "notas_civicas": "País hinduista. Respetar templos. Propinas habituales para guías.",
        "requisitos_especiales": [
            "Permiso de trekking para zonas restringidas (Annapurna, Everest)",
            "Aclimatación imprescindible — no subir más de 500m/día sobre 3000m",
        ],
        "alertas_maec": ["Terremotos frecuentes — zona sísmica alta"],
        "fuentes_prensa": [
            {"nombre": "Kathmandu Post", "url": "https://kathmandupost.com/rss", "idioma": "EN"},
            {"nombre": "My Republica", "url": "https://myrepublica.nagariknetwork.com/feed/", "idioma": "EN"},
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # AFRICA (ampliación)
    # ══════════════════════════════════════════════════════════════════════════

    "Kenia": {
        "region": "África", "emoji": "🇰🇪", "capital": "Nairobi",
        "moneda_nombre": "Chelín keniano", "moneda_codigo": "KES", "nivel_riesgo_maec": 3,
        "lat": -1.2921, "lon": 36.8219, "timezone": "Africa/Nairobi",
        "idioma": "Suajili / Inglés", "idioma_oficial": "Suajili, Inglés",
        "enchufes": "Tipo G (3 patillas)", "voltaje": "240V", "frecuencia": "50Hz",
        "internet_calidad": "Buena (ciudades)", "conduccion_lado": "Izquierda", "distancia_sistema": "Métrico",
        "telefono_emergencias": "999 / 112", "telefono_policia": "999",
        "telefono_embajada_es": "+254 20 420 3036",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/nairobi/es/Paginas/inicio.aspx",
        "visa_espana": "Requerida (eVisa online)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Fiebre amarilla", "Hepatitis A", "Tifoidea", "Rabia", "Meningitis"],
        "vacunas_obligatorias": ["Fiebre amarilla (si llega de zona endémica)"],
        "riesgo_salud": "Alto", "riesgo_malaria": "Alto",
        "notas_salud": "Malaria — profilaxis obligatoria. No beber agua del grifo. Dentista y médico antes de partir.",
        "notas_civicas": "No fotografiar edificios gubernamentales. Robos en Nairobi (Eastleigh, CBD) — precaución.",
        "requisitos_especiales": ["eVisa obligatoria — etakenya.go.ke"],
        "alertas_maec": [
            "Frontera Somalia y zona costera norte — alto riesgo terrorista (Al-Shabaab)",
            "Precaución en Nairobi — robos y atracos",
        ],
        "fuentes_prensa": [
            {"nombre": "Daily Nation Kenya", "url": "https://nation.africa/kenya/rss", "idioma": "EN"},
            {"nombre": "The Standard Kenya", "url": "https://www.standardmedia.co.ke/rss/all", "idioma": "EN"},
        ],
    },

    "Tanzania": {
        "region": "África", "emoji": "🇹🇿", "capital": "Dodoma",
        "moneda_nombre": "Chelín tanzano", "moneda_codigo": "TZS", "nivel_riesgo_maec": 2,
        "lat": -6.3690, "lon": 34.8888, "timezone": "Africa/Dar_es_Salaam",
        "idioma": "Suajili / Inglés", "idioma_oficial": "Suajili, Inglés",
        "enchufes": "Tipo D / Tipo G", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Moderada", "conduccion_lado": "Izquierda", "distancia_sistema": "Métrico",
        "telefono_emergencias": "112", "telefono_policia": "112",
        "telefono_embajada_es": "+255 22 211 4787",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/nairobi/es/Paginas/inicio.aspx",
        "visa_espana": "Requerida (eVisa online)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Fiebre amarilla", "Hepatitis A", "Tifoidea", "Rabia"],
        "vacunas_obligatorias": ["Fiebre amarilla"],
        "riesgo_salud": "Alto", "riesgo_malaria": "Alto",
        "notas_salud": "Malaria — profilaxis imprescindible. Kilimanjaro — aclimatación y guía obligatorio.",
        "notas_civicas": "Zanzibar — isla mayoritariamente musulmana, vestimenta modesta. No fotografiar personas sin permiso.",
        "requisitos_especiales": ["Certificado fiebre amarilla obligatorio"],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "The Citizen Tanzania", "url": "https://www.thecitizen.co.tz/tanzania/rss", "idioma": "EN"},
            {"nombre": "Daily News Tanzania", "url": "https://dailynews.co.tz/feed/", "idioma": "EN"},
        ],
    },

    "Sudáfrica": {
        "region": "África", "emoji": "🇿🇦", "capital": "Pretoria",
        "moneda_nombre": "Rand sudafricano", "moneda_codigo": "ZAR", "nivel_riesgo_maec": 3,
        "lat": -25.7479, "lon": 28.2293, "timezone": "Africa/Johannesburg",
        "idioma": "11 idiomas oficiales (Zulú, Xhosa, Afrikáans, Inglés...)", "idioma_oficial": "11 idiomas",
        "enchufes": "Tipo M (3 clavijas grandes) / Tipo N", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Buena (ciudades)", "conduccion_lado": "Izquierda", "distancia_sistema": "Métrico",
        "telefono_emergencias": "112 / 10111", "telefono_policia": "10111",
        "telefono_embajada_es": "+27 12 460 0123",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/pretoria/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 90 días)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Hepatitis A", "Fiebre amarilla (si llega de zona endémica)"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado", "riesgo_malaria": "Moderado (Kruger, Limpopo, KwaZulu-Natal norte)",
        "notas_salud": "Malaria en parques del norte — profilaxis. VIH: alta prevalencia — precaución.",
        "notas_civicas": "No parar en semáforos de noche (smash and grab). No mostrar objetos de valor. Safari — seguir instrucciones guía.",
        "requisitos_especiales": ["Menores: llevar acta de nacimiento y autorización si viajan sin ambos progenitores"],
        "alertas_maec": [
            "Alta criminalidad urbana — precaución extrema en Johannesburgo y Cape Town",
            "Cortes de electricidad (load shedding) frecuentes",
        ],
        "fuentes_prensa": [
            {"nombre": "Daily Maverick", "url": "https://www.dailymaverick.co.za/feed/", "idioma": "EN"},
            {"nombre": "Mail & Guardian", "url": "https://mg.co.za/feed/", "idioma": "EN"},
        ],
    },

    "Ghana": {
        "region": "África", "emoji": "🇬🇭", "capital": "Acra",
        "moneda_nombre": "Cedi ghanés", "moneda_codigo": "GHS", "nivel_riesgo_maec": 2,
        "lat": 5.6037, "lon": -0.1870, "timezone": "Africa/Accra",
        "idioma": "Inglés / Akan", "idioma_oficial": "Inglés",
        "enchufes": "Tipo D / Tipo G", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Moderada", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "112 / 193", "telefono_policia": "191",
        "telefono_embajada_es": "+233 30 274 1460",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/abidjan/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 90 días)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Fiebre amarilla", "Hepatitis A", "Tifoidea", "Meningitis", "Rabia"],
        "vacunas_obligatorias": ["Fiebre amarilla"],
        "riesgo_salud": "Alto", "riesgo_malaria": "Alto",
        "notas_salud": "Malaria — profilaxis imprescindible. No beber agua del grifo.",
        "notas_civicas": "País relativamente estable para la región. Hospitalidad notable.",
        "requisitos_especiales": ["Certificado fiebre amarilla obligatorio"],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "Ghana Web", "url": "https://www.ghanaweb.com/GhanaHomePage/rss/headlines.xml", "idioma": "EN"},
            {"nombre": "Graphic Online", "url": "https://www.graphic.com.gh/feed", "idioma": "EN"},
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # AMERICA (ampliación)
    # ══════════════════════════════════════════════════════════════════════════

    "Canadá": {
        "region": "América", "emoji": "🇨🇦", "capital": "Ottawa",
        "moneda_nombre": "Dólar canadiense", "moneda_codigo": "CAD", "nivel_riesgo_maec": 1,
        "lat": 45.4215, "lon": -75.6972, "timezone": "America/Toronto",
        "idioma": "Inglés / Francés", "idioma_oficial": "Inglés, Francés",
        "enchufes": "Tipo A / Tipo B", "voltaje": "120V", "frecuencia": "60Hz",
        "internet_calidad": "Excelente", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "911", "telefono_policia": "911",
        "telefono_embajada_es": "+1 613 747 2252",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/ottawa/es/Paginas/inicio.aspx",
        "visa_espana": "eTA obligatoria (vuelos, 7 CAD online)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Muy bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "Sistema sanitario excelente. Seguro médico muy recomendable (caro para extranjeros).",
        "notas_civicas": "Propinas 15-20%. Inviernos muy duros. Naturaleza salvaje — precaución en parques.",
        "requisitos_especiales": ["eTA obligatoria para vuelos — tramitar en canada.ca"],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "CBC News", "url": "https://www.cbc.ca/cmlink/rss-topstories", "idioma": "EN"},
            {"nombre": "Globe and Mail", "url": "https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/canada/", "idioma": "EN"},
        ],
    },

    "Brasil": {
        "region": "América", "emoji": "🇧🇷", "capital": "Brasilia",
        "moneda_nombre": "Real brasileño", "moneda_codigo": "BRL", "nivel_riesgo_maec": 2,
        "lat": -15.7801, "lon": -47.9292, "timezone": "America/Sao_Paulo",
        "idioma": "Portugués", "idioma_oficial": "Portugués",
        "enchufes": "Tipo N (estándar brasileño)", "voltaje": "127V/220V (varía por estado)", "frecuencia": "60Hz",
        "internet_calidad": "Buena (ciudades)", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "192 (SAMU)", "telefono_policia": "190",
        "telefono_embajada_es": "+55 61 3242 4284",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/brasilia/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 90 días)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Fiebre amarilla (Amazonia)", "Hepatitis A", "Tifoidea", "Rabia"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado", "riesgo_malaria": "Moderado (Amazonia)",
        "notas_salud": "Dengue, Zika y Chikungunya presentes. Fiebre amarilla imprescindible para Amazonia.",
        "notas_civicas": "No mostrar joyas ni móvil en calle. Favelas — no entrar sin guía local. Carnaval — precaución máxima.",
        "requisitos_especiales": [],
        "alertas_maec": [
            "Alta criminalidad en grandes ciudades (Río, São Paulo, Salvador)",
            "Evitar favelas sin guía local de confianza",
        ],
        "fuentes_prensa": [
            {"nombre": "Folha de São Paulo", "url": "https://feeds.folha.uol.com.br/emcimadahora/rss091.xml", "idioma": "PT"},
            {"nombre": "O Globo", "url": "https://oglobo.globo.com/rss.xml", "idioma": "PT"},
            {"nombre": "Brazil Reports", "url": "https://brazilreports.com/feed/", "idioma": "EN"},
        ],
    },

    "Chile": {
        "region": "América", "emoji": "🇨🇱", "capital": "Santiago",
        "moneda_nombre": "Peso chileno", "moneda_codigo": "CLP", "nivel_riesgo_maec": 1,
        "lat": -33.4489, "lon": -70.6693, "timezone": "America/Santiago",
        "idioma": "Español", "idioma_oficial": "Español",
        "enchufes": "Tipo C / Tipo L", "voltaje": "220V", "frecuencia": "50Hz",
        "internet_calidad": "Muy buena", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "131 (SAMU)", "telefono_policia": "133",
        "telefono_embajada_es": "+56 2 2235 2754",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/santiago/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida", "pasaporte_o_dni": "Pasaporte o DNI",
        "vacunas_recomendadas": ["Hepatitis A"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "Sistema sanitario bueno. Zona Atacama — protección solar extrema.",
        "notas_civicas": "País muy ordenado. Inviernos duros en Patagonia. Zona sísmica.",
        "requisitos_especiales": [],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "La Tercera", "url": "https://www.latercera.com/feed/", "idioma": "ES"},
            {"nombre": "El Mostrador", "url": "https://www.elmostrador.cl/feed/", "idioma": "ES"},
        ],
    },

    "Perú": {
        "region": "América", "emoji": "🇵🇪", "capital": "Lima",
        "moneda_nombre": "Sol peruano", "moneda_codigo": "PEN", "nivel_riesgo_maec": 2,
        "lat": -12.0464, "lon": -77.0428, "timezone": "America/Lima",
        "idioma": "Español / Quechua / Aimara", "idioma_oficial": "Español, Quechua",
        "enchufes": "Tipo A / Tipo B / Tipo C", "voltaje": "220V", "frecuencia": "60Hz",
        "internet_calidad": "Buena (ciudades)", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "117 (SAMU)", "telefono_policia": "105",
        "telefono_embajada_es": "+51 1 513 7930",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/lima/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 183 días)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Fiebre amarilla (Amazonia)", "Hepatitis A", "Tifoidea", "Rabia"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado", "riesgo_malaria": "Moderado (Amazonia, <2500m)",
        "notas_salud": "Altitud: Cusco 3400m, Machu Picchu 2430m — aclimatación en Lima primero. Soroche (mal de altura) frecuente.",
        "notas_civicas": "Taxis — usar apps (InDriver, Uber). No mostrar objetos de valor. Mercados: regateo habitual.",
        "requisitos_especiales": [],
        "alertas_maec": [
            "Inestabilidad política frecuente — posibles protestas y bloqueos",
            "Algunas zonas cocaleras — evitar (VRAEM)",
        ],
        "fuentes_prensa": [
            {"nombre": "El Comercio Perú", "url": "https://elcomercio.pe/arc/outboundfeeds/rss/", "idioma": "ES"},
            {"nombre": "Peru Reports", "url": "https://perureports.com/feed/", "idioma": "EN"},
        ],
    },

    "Cuba": {
        "region": "América", "emoji": "🇨🇺", "capital": "La Habana",
        "moneda_nombre": "Peso cubano", "moneda_codigo": "CUP", "nivel_riesgo_maec": 2,
        "lat": 23.1136, "lon": -82.3666, "timezone": "America/Havana",
        "idioma": "Español", "idioma_oficial": "Español",
        "enchufes": "Tipo A / Tipo B / Tipo C", "voltaje": "110V/220V", "frecuencia": "60Hz",
        "internet_calidad": "Muy limitada", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "104 (ambulancia)", "telefono_policia": "106",
        "telefono_embajada_es": "+53 7 866 8025",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/lahavana/es/Paginas/inicio.aspx",
        "visa_espana": "Tarjeta de turista obligatoria (comprar antes)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado", "riesgo_malaria": "Ninguno",
        "notas_salud": "Dengue presente. Escasez de medicamentos — llevar botiquín completo. Seguro médico obligatorio.",
        "notas_civicas": "Escasez de productos básicos. Dos monedas (CUP/USD) — confuso. Internet muy limitada.",
        "requisitos_especiales": [
            "Seguro médico obligatorio — lo comprueban en frontera",
            "Tarjeta de turista — comprar en aeropuerto o agencia",
        ],
        "alertas_maec": [
            "Escasez grave de productos básicos, combustible y alimentos",
            "Cortes de luz frecuentes y prolongados",
        ],
        "fuentes_prensa": [
            {"nombre": "14ymedio", "url": "https://www.14ymedio.com/feed/", "idioma": "ES"},
            {"nombre": "CiberCuba", "url": "https://www.cibercuba.com/feed", "idioma": "ES"},
        ],
    },

    "Rep. Dominicana": {
        "region": "América", "emoji": "🇩🇴", "capital": "Santo Domingo",
        "moneda_nombre": "Peso dominicano", "moneda_codigo": "DOP", "nivel_riesgo_maec": 2,
        "lat": 18.4861, "lon": -69.9312, "timezone": "America/Santo_Domingo",
        "idioma": "Español", "idioma_oficial": "Español",
        "enchufes": "Tipo A / Tipo B", "voltaje": "110V", "frecuencia": "60Hz",
        "internet_calidad": "Buena (zonas turísticas)", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "911", "telefono_policia": "911",
        "telefono_embajada_es": "+1 809 535 6500",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/santodomingo/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 30 días incluidos en e-Ticket)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado", "riesgo_malaria": "Bajo",
        "notas_salud": "Dengue presente. No beber agua del grifo. e-Ticket obligatorio.",
        "notas_civicas": "Zonas turísticas (Punta Cana, Samaná) seguras. Fuera de ellas, precaución.",
        "requisitos_especiales": ["e-Ticket obligatorio — eticket.migracion.gob.do"],
        "alertas_maec": ["Criminalidad fuera de zonas turísticas"],
        "fuentes_prensa": [
            {"nombre": "Listín Diario", "url": "https://listindiario.com/feed/", "idioma": "ES"},
            {"nombre": "Diario Libre", "url": "https://www.diariolibre.com/feed/", "idioma": "ES"},
        ],
    },

    "Ecuador": {
        "region": "América", "emoji": "🇪🇨", "capital": "Quito",
        "moneda_nombre": "Dólar estadounidense", "moneda_codigo": "USD", "nivel_riesgo_maec": 3,
        "lat": -0.1807, "lon": -78.4678, "timezone": "America/Guayaquil",
        "idioma": "Español", "idioma_oficial": "Español",
        "enchufes": "Tipo A / Tipo B", "voltaje": "120V", "frecuencia": "60Hz",
        "internet_calidad": "Buena (ciudades)", "conduccion_lado": "Derecha", "distancia_sistema": "Métrico",
        "telefono_emergencias": "911", "telefono_policia": "101",
        "telefono_embajada_es": "+593 2 220 9720",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/quito/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 90 días)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Fiebre amarilla", "Hepatitis A", "Tifoidea", "Rabia"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado", "riesgo_malaria": "Bajo (costa y Amazonia)",
        "notas_salud": "Quito a 2850m — aclimatación. No beber agua del grifo.",
        "notas_civicas": "Situación de seguridad deteriorada en 2023-2024. Precaución extrema.",
        "requisitos_especiales": [],
        "alertas_maec": [
            "Violencia narco en auge — precaución en todo el país",
            "Guayaquil y zonas costeras — alto riesgo",
            "Estado de excepción intermitente",
        ],
        "fuentes_prensa": [
            {"nombre": "El Universo", "url": "https://www.eluniverso.com/arc/outboundfeeds/rss/", "idioma": "ES"},
            {"nombre": "El Comercio Ecuador", "url": "https://www.elcomercio.com/feed/", "idioma": "ES"},
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # OCEANÍA (ampliación)
    # ══════════════════════════════════════════════════════════════════════════

    "Nueva Zelanda": {
        "region": "Oceanía", "emoji": "🇳🇿", "capital": "Wellington",
        "moneda_nombre": "Dólar neozelandés", "moneda_codigo": "NZD", "nivel_riesgo_maec": 1,
        "lat": -41.2865, "lon": 174.7762, "timezone": "Pacific/Auckland",
        "idioma": "Inglés / Maorí", "idioma_oficial": "Inglés, Maorí, NZ Sign Language",
        "enchufes": "Tipo I", "voltaje": "230V", "frecuencia": "50Hz",
        "internet_calidad": "Muy buena", "conduccion_lado": "Izquierda", "distancia_sistema": "Métrico",
        "telefono_emergencias": "111", "telefono_policia": "111",
        "telefono_embajada_es": "+64 4 802 5665",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/canberra/es/Paginas/inicio.aspx",
        "visa_espana": "NZeTA obligatoria (23 NZD online)", "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Muy bajo", "riesgo_malaria": "Ninguno",
        "notas_salud": "Sistema sanitario excelente. UV muy alto.",
        "notas_civicas": "Bioseguridad muy estricta (declarar todo). Cultura maorí — respetar. Naturaleza impresionante.",
        "requisitos_especiales": [
            "NZeTA obligatoria — nzeta.immigration.govt.nz",
            "International Visitor Conservation and Tourism Levy (IVL): 35 NZD",
            "Bioseguridad muy estricta — declarar alimentos, plantas, tierra",
        ],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "RNZ News", "url": "https://www.rnz.co.nz/rss/news.xml", "idioma": "EN"},
            {"nombre": "NZ Herald", "url": "https://www.nzherald.co.nz/arc/outboundfeeds/rss/section/news/", "idioma": "EN"},
        ],
    },


    "Rusia": {
        "region": "Europa",
        "emoji": "🇷🇺",
        "capital": "Moscú",
        "moneda_nombre": "Rublo ruso",
        "moneda_codigo": "RUB",
        "nivel_riesgo_maec": 5,
        "lat": 55.7558, "lon": 37.6173,
        "timezone": "Europe/Moscow",
        "idioma": "Ruso",
        "idioma_oficial": "Ruso",
        "enchufes": "Tipo C / Tipo F",
        "voltaje": "220V",
        "frecuencia": "50Hz",
        "internet_calidad": "Restringida (RuNet — múltiples servicios bloqueados)",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "112",
        "telefono_policia": "102",
        "telefono_embajada_es": "+7 495 937 7060",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/moscu/es/Paginas/inicio.aspx",
        "visa_espana": "Requerida (muy difícil de obtener en contexto actual)",
        "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Encefalitis transmitida por garrapatas (zonas boscosas)", "Hepatitis A"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "Sistema sanitario desigual. Inviernos extremos (-20°C o menos en Moscú). Llevar medicación propia.",
        "notas_civicas": "Fotografiar instalaciones militares, gubernamentales o infraestructuras críticas es ilegal y puede derivar en detención. Redes sociales occidentales bloqueadas (Instagram, Facebook). VPN muy restringidas.",
        "requisitos_especiales": [
            "Visado prácticamente inaccesible para ciudadanos españoles en contexto actual (2024-2026)",
            "Registro obligatorio en policía local en 7 días (lo hace el hotel)",
            "Sanciones internacionales activas — tarjetas bancarias occidentales no funcionan",
            "Servicio militar obligatorio para ciudadanos rusos — riesgo de movilización",
        ],
        "alertas_maec": [
            "⛔ VIAJE TOTALMENTE DESACONSEJADO — Nivel 5/5 MAEC",
            "Conflicto armado activo (guerra en Ucrania) con riesgo de escalada",
            "Detenciones arbitrarias de ciudadanos extranjeros documentadas",
            "Sanciones internacionales: tarjetas VISA/Mastercard no operativas",
            "Vuelos directos desde España suspendidos — espacio aéreo cerrado parcialmente",
            "Riesgo de movilización forzosa si se tiene doble nacionalidad rusa",
            "Legislación represiva: crítica al gobierno o al ejército — hasta 15 años de prisión",
        ],
        "fuentes_prensa": [
            {"nombre": "Meduza (independiente en exilio)", "url": "https://meduza.io/rss/all", "idioma": "RU/EN"},
            {"nombre": "The Moscow Times", "url": "https://www.themoscowtimes.com/rss/news", "idioma": "EN"},
            {"nombre": "iStories (investigación)", "url": "https://istories.media/feed/", "idioma": "RU"},
        ],
    },

}