"""
config/paises.py — Catálogo de países TripOSINT
Campos por país:
  Obligatorios: region, emoji, capital, moneda_nombre, moneda_codigo,
                nivel_riesgo_maec (1-5)
  Meteo:        lat, lon, timezone
  Info:         idioma, enchufes, voltaje, frecuencia, internet_calidad,
                conduccion_lado, distancia_sistema
  Contactos:    telefono_emergencias, telefono_policia, telefono_embajada_es,
                url_maec
  Salud:        vacunas_recomendadas, vacunas_obligatorias, riesgo_salud,
                riesgo_malaria, notas_salud
  Cívico:       notas_civicas, requisitos_especiales, alertas_maec
  Prensa RSS:   fuentes_prensa [{nombre, url, idioma}]
"""

PAISES = {

    # ══════════════════════════════════════════════════════════════════════════
    # EUROPA
    # ══════════════════════════════════════════════════════════════════════════

    "Alemania": {
        "region": "Europa",
        "emoji": "🇩🇪",
        "capital": "Berlín",
        "moneda_nombre": "Euro",
        "moneda_codigo": "EUR",
        "nivel_riesgo_maec": 1,
        # Meteo
        "lat": 52.52, "lon": 13.405,
        "timezone": "Europe/Berlin",
        # Info
        "idioma": "Alemán",
        "idioma_oficial": "Alemán",
        "enchufes": "Tipo F (Schuko)",
        "voltaje": "230V",
        "frecuencia": "50Hz",
        "internet_calidad": "Excelente",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        # Contactos
        "telefono_emergencias": "112",
        "telefono_policia": "110",
        "telefono_embajada_es": "+49 30 254007-0",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/berlin/es/Paginas/inicio.aspx",
        # Entrada
        "visa_espana": "No requerida (Schengen)",
        "pasaporte_o_dni": "DNI válido",
        # Salud
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "Sistema sanitario de alta calidad. TARJETA SANITARIA EUROPEA válida.",
        # Cívico
        "notas_civicas": "Puntualidad muy valorada. Separación estricta de basura obligatoria. Silencio en domingos (Ruhezeit).",
        "requisitos_especiales": [],
        "alertas_maec": [],
        # Prensa
        "fuentes_prensa": [
            {"nombre": "Der Spiegel International", "url": "https://www.spiegel.de/international/index.rss", "idioma": "EN"},
            {"nombre": "DW Noticias", "url": "https://rss.dw.com/rdf/rss-es-all", "idioma": "ES"},
            {"nombre": "Deutsche Welle World", "url": "https://rss.dw.com/rdf/rss-en-top", "idioma": "EN"},
        ],
    },

    "Francia": {
        "region": "Europa",
        "emoji": "🇫🇷",
        "capital": "París",
        "moneda_nombre": "Euro",
        "moneda_codigo": "EUR",
        "nivel_riesgo_maec": 1,
        "lat": 48.8566, "lon": 2.3522,
        "timezone": "Europe/Paris",
        "idioma": "Francés",
        "idioma_oficial": "Francés",
        "enchufes": "Tipo E",
        "voltaje": "230V",
        "frecuencia": "50Hz",
        "internet_calidad": "Muy buena",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "112",
        "telefono_policia": "17",
        "telefono_embajada_es": "+33 1 44 43 18 00",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/paris/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (Schengen)",
        "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "TARJETA SANITARIA EUROPEA válida. Alta calidad asistencial.",
        "notas_civicas": "Saludo formal obligatorio en comercios (Bonjour/Bonsoir). Las propinas no son obligatorias pero se valoran.",
        "requisitos_especiales": [],
        "alertas_maec": ["Vigilancia elevada por amenaza terrorista (Plan Vigipirate)"],
        "fuentes_prensa": [
            {"nombre": "Le Monde", "url": "https://www.lemonde.fr/rss/une.xml", "idioma": "FR"},
            {"nombre": "France 24 ES", "url": "https://www.france24.com/es/rss", "idioma": "ES"},
            {"nombre": "RFI Español", "url": "https://www.rfi.fr/es/rss", "idioma": "ES"},
        ],
    },

    "Italia": {
        "region": "Europa",
        "emoji": "🇮🇹",
        "capital": "Roma",
        "moneda_nombre": "Euro",
        "moneda_codigo": "EUR",
        "nivel_riesgo_maec": 1,
        "lat": 41.9028, "lon": 12.4964,
        "timezone": "Europe/Rome",
        "idioma": "Italiano",
        "idioma_oficial": "Italiano",
        "enchufes": "Tipo F / Tipo L",
        "voltaje": "230V",
        "frecuencia": "50Hz",
        "internet_calidad": "Buena",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "112",
        "telefono_policia": "113",
        "telefono_embajada_es": "+39 06 6840401",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/roma/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (Schengen)",
        "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "TARJETA SANITARIA EUROPEA válida.",
        "notas_civicas": "Evitar entrada a iglesias sin hombros y rodillas cubiertos. Codice del Turista en ciudades históricas.",
        "requisitos_especiales": ["Algunas ciudades cobran tasa turística (1-6€/noche)"],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "ANSA News", "url": "https://www.ansa.it/sito/notizie/mondo/mondo_rss.xml", "idioma": "IT"},
            {"nombre": "La Repubblica", "url": "https://www.repubblica.it/rss/homepage/rss2.0.xml", "idioma": "IT"},
            {"nombre": "Corriere della Sera", "url": "https://xml2.corriereobjects.it/rss/homepage.xml", "idioma": "IT"},
        ],
    },

    "Reino Unido": {
        "region": "Europa",
        "emoji": "🇬🇧",
        "capital": "Londres",
        "moneda_nombre": "Libra esterlina",
        "moneda_codigo": "GBP",
        "nivel_riesgo_maec": 1,
        "lat": 51.5074, "lon": -0.1278,
        "timezone": "Europe/London",
        "idioma": "Inglés",
        "idioma_oficial": "Inglés",
        "enchufes": "Tipo G (3 patillas)",
        "voltaje": "230V",
        "frecuencia": "50Hz",
        "internet_calidad": "Excelente",
        "conduccion_lado": "Izquierda",
        "distancia_sistema": "Imperial (millas)",
        "telefono_emergencias": "999",
        "telefono_policia": "101 (no urgente)",
        "telefono_embajada_es": "+44 20 7235 5555",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/londres/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 6 meses, post-Brexit)",
        "pasaporte_o_dni": "Pasaporte (DNI no válido desde 2021)",
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "NHS disponible para emergencias. Recomendable seguro privado para no residentes.",
        "notas_civicas": "Hacer cola es norma social estricta. Propinas 10-15% en restaurantes. Conducción por la izquierda.",
        "requisitos_especiales": [
            "Pasaporte obligatorio (DNI no aceptado desde Brexit)",
            "Máximo 6 meses sin visado para turismo",
        ],
        "alertas_maec": ["Amenaza terrorista considerable (nivel SUBSTANTIAL)"],
        "fuentes_prensa": [
            {"nombre": "BBC News World", "url": "http://feeds.bbci.co.uk/news/world/rss.xml", "idioma": "EN"},
            {"nombre": "The Guardian World", "url": "https://www.theguardian.com/world/rss", "idioma": "EN"},
            {"nombre": "Reuters UK", "url": "https://feeds.reuters.com/reuters/UKdomesticNews", "idioma": "EN"},
        ],
    },

    "Turquía": {
        "region": "Europa",
        "emoji": "🇹🇷",
        "capital": "Ankara",
        "moneda_nombre": "Lira turca",
        "moneda_codigo": "TRY",
        "nivel_riesgo_maec": 2,
        "lat": 39.9334, "lon": 32.8597,
        "timezone": "Europe/Istanbul",
        "idioma": "Turco",
        "idioma_oficial": "Turco",
        "enchufes": "Tipo F (Schuko)",
        "voltaje": "230V",
        "frecuencia": "50Hz",
        "internet_calidad": "Buena (con restricciones)",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "112",
        "telefono_policia": "155",
        "telefono_embajada_es": "+90 312 440 35 60",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/ankara/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 90 días)",
        "pasaporte_o_dni": "Pasaporte o DNI",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea", "Hepatitis B"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado",
        "riesgo_malaria": "Muy bajo (zonas rurales sureste)",
        "notas_salud": "Agua del grifo no recomendada. Calor extremo en verano. Hospitales privados de buena calidad en ciudades.",
        "notas_civicas": "Respetar costumbres islámicas (Ramadán, mezquitas). Algunas redes sociales pueden estar restringidas.",
        "requisitos_especiales": ["Compra de lira turca solo en cambio oficial"],
        "alertas_maec": [
            "Precaución en zonas fronterizas con Siria e Irak",
            "Riesgo de atentados terroristas en zonas turísticas",
            "Restricciones en algunas redes sociales",
        ],
        "fuentes_prensa": [
            {"nombre": "Hurriyet Daily News", "url": "https://www.hurriyetdailynews.com/rss.aspx", "idioma": "EN"},
            {"nombre": "Daily Sabah", "url": "https://www.dailysabah.com/rss", "idioma": "EN"},
            {"nombre": "TRT World", "url": "https://www.trtworld.com/rss", "idioma": "EN"},
        ],
    },

    "Portugal": {
        "region": "Europa",
        "emoji": "🇵🇹",
        "capital": "Lisboa",
        "moneda_nombre": "Euro",
        "moneda_codigo": "EUR",
        "nivel_riesgo_maec": 1,
        "lat": 38.7223, "lon": -9.1393,
        "timezone": "Europe/Lisbon",
        "idioma": "Portugués",
        "idioma_oficial": "Portugués",
        "enchufes": "Tipo F (Schuko)",
        "voltaje": "230V",
        "frecuencia": "50Hz",
        "internet_calidad": "Muy buena",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "112",
        "telefono_policia": "112",
        "telefono_embajada_es": "+351 21 347 2381",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/lisboa/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (Schengen)",
        "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "TARJETA SANITARIA EUROPEA válida. Sistema sanitario de calidad.",
        "notas_civicas": "País muy seguro. Atención a carteristas en zonas turísticas de Lisboa y Oporto.",
        "requisitos_especiales": [],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "Público", "url": "https://feeds.feedburner.com/PublicoRSS", "idioma": "PT"},
            {"nombre": "Observador", "url": "https://observador.pt/feed/", "idioma": "PT"},
            {"nombre": "RTP Notícias", "url": "https://www.rtp.pt/noticias/rss", "idioma": "PT"},
        ],
    },

    "Grecia": {
        "region": "Europa",
        "emoji": "🇬🇷",
        "capital": "Atenas",
        "moneda_nombre": "Euro",
        "moneda_codigo": "EUR",
        "nivel_riesgo_maec": 1,
        "lat": 37.9838, "lon": 23.7275,
        "timezone": "Europe/Athens",
        "idioma": "Griego",
        "idioma_oficial": "Griego",
        "enchufes": "Tipo F (Schuko)",
        "voltaje": "230V",
        "frecuencia": "50Hz",
        "internet_calidad": "Buena",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "112",
        "telefono_policia": "100",
        "telefono_embajada_es": "+30 21 0345 6100",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/atenas/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (Schengen)",
        "pasaporte_o_dni": "DNI válido",
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "TARJETA SANITARIA EUROPEA válida. Calor extremo en verano.",
        "notas_civicas": "Atención a estafas a turistas en Atenas. Respeto a lugares religiosos.",
        "requisitos_especiales": [],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "Ekathimerini", "url": "https://www.ekathimerini.com/rss/latest", "idioma": "EN"},
            {"nombre": "Greek Reporter", "url": "https://greekreporter.com/feed/", "idioma": "EN"},
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # AMÉRICA
    # ══════════════════════════════════════════════════════════════════════════

    "México": {
        "region": "América",
        "emoji": "🇲🇽",
        "capital": "Ciudad de México",
        "moneda_nombre": "Peso mexicano",
        "moneda_codigo": "MXN",
        "nivel_riesgo_maec": 3,
        "lat": 19.4326, "lon": -99.1332,
        "timezone": "America/Mexico_City",
        "idioma": "Español",
        "idioma_oficial": "Español",
        "enchufes": "Tipo A / Tipo B",
        "voltaje": "127V",
        "frecuencia": "60Hz",
        "internet_calidad": "Buena (ciudades)",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "911",
        "telefono_policia": "911",
        "telefono_embajada_es": "+52 55 5282 2974",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/mexico/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida",
        "pasaporte_o_dni": "Pasaporte (DNI no recomendado)",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea", "Rabia (zonas rurales)"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado",
        "riesgo_malaria": "Bajo (zonas rurales)",
        "notas_salud": "No beber agua del grifo. Precaución con comida callejera. Altitud en CDMX (2240m) puede causar mal de altura.",
        "notas_civicas": "Evitar zonas de alta criminalidad. No sacar el móvil en la calle. Usar taxis seguros (UBER recomendado).",
        "requisitos_especiales": [
            "Formulario de migración (puede ser digital)",
            "Seguro de viaje muy recomendable",
        ],
        "alertas_maec": [
            "Alta tasa de criminalidad en algunos estados (Guerrero, Michoacán, Tamaulipas)",
            "Evitar circular de noche en carreteras secundarias",
            "Riesgo de extorsión y secuestro exprés en zonas urbanas",
        ],
        "fuentes_prensa": [
            {"nombre": "El Universal", "url": "https://www.eluniversal.com.mx/rss.xml", "idioma": "ES"},
            {"nombre": "Proceso", "url": "https://www.proceso.com.mx/rss/noticias", "idioma": "ES"},
            {"nombre": "Animal Político", "url": "https://www.animalpolitico.com/feed", "idioma": "ES"},
        ],
    },

    "Colombia": {
        "region": "América",
        "emoji": "🇨🇴",
        "capital": "Bogotá",
        "moneda_nombre": "Peso colombiano",
        "moneda_codigo": "COP",
        "nivel_riesgo_maec": 3,
        "lat": 4.711, "lon": -74.0721,
        "timezone": "America/Bogota",
        "idioma": "Español",
        "idioma_oficial": "Español",
        "enchufes": "Tipo A / Tipo B",
        "voltaje": "110V",
        "frecuencia": "60Hz",
        "internet_calidad": "Buena (ciudades)",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "123",
        "telefono_policia": "112",
        "telefono_embajada_es": "+57 1 622 0090",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/bogota/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida",
        "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Fiebre amarilla", "Hepatitis A", "Tifoidea", "Rabia"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado",
        "riesgo_malaria": "Moderado (selva y costa)",
        "notas_salud": "Vacuna fiebre amarilla recomendada para zonas amazónicas. Altitud de Bogotá (2640m).",
        "notas_civicas": "Evitar zonas conflictivas. No mostrar joyas u objetos de valor en la calle.",
        "requisitos_especiales": ["Certificado fiebre amarilla si llega de zona endémica"],
        "alertas_maec": [
            "Zonas de conflicto armado (FARC disidentes, ELN)",
            "Alta criminalidad en algunas zonas urbanas",
            "Evitar departamentos: Chocó, Arauca, Norte de Santander frontera Venezuela",
        ],
        "fuentes_prensa": [
            {"nombre": "El Tiempo", "url": "https://www.eltiempo.com/rss/noticias.xml", "idioma": "ES"},
            {"nombre": "El Espectador", "url": "https://www.elespectador.com/feed/", "idioma": "ES"},
            {"nombre": "Semana", "url": "https://www.semana.com/rss-feed/", "idioma": "ES"},
        ],
    },

    "Argentina": {
        "region": "América",
        "emoji": "🇦🇷",
        "capital": "Buenos Aires",
        "moneda_nombre": "Peso argentino",
        "moneda_codigo": "ARS",
        "nivel_riesgo_maec": 2,
        "lat": -34.6037, "lon": -58.3816,
        "timezone": "America/Argentina/Buenos_Aires",
        "idioma": "Español",
        "idioma_oficial": "Español",
        "enchufes": "Tipo I (3 clavijas triangulares)",
        "voltaje": "220V",
        "frecuencia": "50Hz",
        "internet_calidad": "Buena",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "911",
        "telefono_policia": "101",
        "telefono_embajada_es": "+54 11 4819 2400",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/buenosaires/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida",
        "pasaporte_o_dni": "Pasaporte o DNI español",
        "vacunas_recomendadas": ["Hepatitis A"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "Alta calidad médica en Buenos Aires. Precaución con dengue en temporada.",
        "notas_civicas": "Situación económica compleja. Llevar dólares o euros para mejor tipo de cambio (dólar blue). Precaución con carteristas en BA.",
        "requisitos_especiales": ["Tipo de cambio oficial vs. informal — informarse bien"],
        "alertas_maec": [
            "Inestabilidad económica — planificar bien gastos",
            "Carteristas y robos en zona turística de Buenos Aires",
        ],
        "fuentes_prensa": [
            {"nombre": "La Nación", "url": "https://www.lanacion.com.ar/arc/outboundfeeds/rss/?outputType=xml", "idioma": "ES"},
            {"nombre": "Infobae", "url": "https://www.infobae.com/feeds/rss/", "idioma": "ES"},
            {"nombre": "Clarín", "url": "https://www.clarin.com/rss/lo-ultimo/", "idioma": "ES"},
        ],
    },

    "Estados Unidos": {
        "region": "América",
        "emoji": "🇺🇸",
        "capital": "Washington D.C.",
        "moneda_nombre": "Dólar estadounidense",
        "moneda_codigo": "USD",
        "nivel_riesgo_maec": 1,
        "lat": 38.9072, "lon": -77.0369,
        "timezone": "America/New_York",
        "idioma": "Inglés",
        "idioma_oficial": "Inglés",
        "enchufes": "Tipo A / Tipo B",
        "voltaje": "120V",
        "frecuencia": "60Hz",
        "internet_calidad": "Excelente",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Imperial (millas, pies)",
        "telefono_emergencias": "911",
        "telefono_policia": "911",
        "telefono_embajada_es": "+1 202 452 0100",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/washington/es/Paginas/inicio.aspx",
        "visa_espana": "ESTA obligatorio (Visa Waiver Program)",
        "pasaporte_o_dni": "Pasaporte (mínimo 6 meses validez)",
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "Seguro médico IMPRESCINDIBLE. Costes sanitarios muy elevados. Llevar medicación con receta.",
        "notas_civicas": "Propinas obligatorias (15-20%). Leyes varían por estado. Consumo alcohol prohibido en la calle en la mayoría de estados.",
        "requisitos_especiales": [
            "ESTA obligatoria — solicitar con mínimo 72h de antelación en esta.cbp.dhs.gov",
            "Seguro médico imprescindible",
            "Declaración aduanera al llegar",
        ],
        "alertas_maec": [],
        "fuentes_prensa": [
            {"nombre": "NPR News", "url": "https://feeds.npr.org/1001/rss.xml", "idioma": "EN"},
            {"nombre": "AP News", "url": "https://rsshub.app/apnews/topics/apf-topnews", "idioma": "EN"},
            {"nombre": "Reuters Top News", "url": "https://feeds.reuters.com/reuters/topNews", "idioma": "EN"},
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # ASIA
    # ══════════════════════════════════════════════════════════════════════════

    "Japón": {
        "region": "Asia",
        "emoji": "🇯🇵",
        "capital": "Tokio",
        "moneda_nombre": "Yen japonés",
        "moneda_codigo": "JPY",
        "nivel_riesgo_maec": 1,
        "lat": 35.6762, "lon": 139.6503,
        "timezone": "Asia/Tokyo",
        "idioma": "Japonés",
        "idioma_oficial": "Japonés",
        "enchufes": "Tipo A / Tipo B",
        "voltaje": "100V",
        "frecuencia": "50/60Hz",
        "internet_calidad": "Excelente",
        "conduccion_lado": "Izquierda",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "119 (ambulancia/bomberos)",
        "telefono_policia": "110",
        "telefono_embajada_es": "+81 3 3583 8531",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/tokio/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 90 días)",
        "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Encefalitis japonesa (zonas rurales)"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Muy bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "Sistema sanitario excelente. Barrera del idioma en hospitales. Llevar medicación propia (restricciones en algunos fármacos).",
        "notas_civicas": "No comer caminando. No hablar por teléfono en transporte público. No propinas (puede ofender). Separar residuos estrictamente.",
        "requisitos_especiales": [
            "Algunos medicamentos comunes en España están prohibidos (pseudoefedrina, codeína)",
            "Declaración aduanera al entrar",
        ],
        "alertas_maec": ["País sísmico — familiarizarse con protocolos de terremoto"],
        "fuentes_prensa": [
            {"nombre": "Japan Times", "url": "https://www.japantimes.co.jp/feed/", "idioma": "EN"},
            {"nombre": "NHK World", "url": "https://www3.nhk.or.jp/rss/news/cat0.xml", "idioma": "EN"},
            {"nombre": "Asahi Shimbun", "url": "https://www.asahi.com/rss/asahi/newsheadlines.rdf", "idioma": "EN"},
        ],
    },

    "India": {
        "region": "Asia",
        "emoji": "🇮🇳",
        "capital": "Nueva Delhi",
        "moneda_nombre": "Rupia india",
        "moneda_codigo": "INR",
        "nivel_riesgo_maec": 2,
        "lat": 28.6139, "lon": 77.2090,
        "timezone": "Asia/Kolkata",
        "idioma": "Hindi / Inglés",
        "idioma_oficial": "Hindi, Inglés",
        "enchufes": "Tipo C / Tipo D / Tipo M",
        "voltaje": "230V",
        "frecuencia": "50Hz",
        "internet_calidad": "Buena (ciudades)",
        "conduccion_lado": "Izquierda",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "112",
        "telefono_policia": "100",
        "telefono_embajada_es": "+91 11 4600 0870",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/nuevadelhi/es/Paginas/inicio.aspx",
        "visa_espana": "Requerida (e-Visa disponible online)",
        "pasaporte_o_dni": "Pasaporte (6 meses mínimo)",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea", "Rabia", "Encefalitis japonesa", "Hepatitis B"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Alto",
        "riesgo_malaria": "Moderado-Alto (zonas rurales y tropicales)",
        "notas_salud": "No beber agua del grifo. Cuidado con comida callejera. Golpe de calor en verano. Contaminación atmosférica grave en Delhi (octubre-marzo).",
        "notas_civicas": "Respetar costumbres religiosas (quitarse los zapatos). Regateo habitual en mercados. Fotografiar personas: pedir permiso.",
        "requisitos_especiales": [
            "e-Visa obligatoria — tramitar con 4 días de antelación",
            "Algunos destinos requieren Restricted Area Permit (RAP)",
        ],
        "alertas_maec": [
            "Zonas de tensión en Cachemira — evitar",
            "Precaución ante acoso a mujeres viajeras",
            "Alta contaminación en Delhi en invierno",
        ],
        "fuentes_prensa": [
            {"nombre": "The Hindu", "url": "https://www.thehindu.com/feeder/default.rss", "idioma": "EN"},
            {"nombre": "NDTV", "url": "https://feeds.feedburner.com/ndtvnews-top-stories", "idioma": "EN"},
            {"nombre": "Times of India", "url": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", "idioma": "EN"},
        ],
    },

    "Tailandia": {
        "region": "Asia",
        "emoji": "🇹🇭",
        "capital": "Bangkok",
        "moneda_nombre": "Baht tailandés",
        "moneda_codigo": "THB",
        "nivel_riesgo_maec": 2,
        "lat": 13.7563, "lon": 100.5018,
        "timezone": "Asia/Bangkok",
        "idioma": "Tailandés",
        "idioma_oficial": "Tailandés",
        "enchufes": "Tipo A / Tipo B / Tipo C",
        "voltaje": "220V",
        "frecuencia": "50Hz",
        "internet_calidad": "Muy buena",
        "conduccion_lado": "Izquierda",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "191",
        "telefono_policia": "191",
        "telefono_embajada_es": "+66 2 661 8284",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/bangkok/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 60 días)",
        "pasaporte_o_dni": "Pasaporte (6 meses mínimo)",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea", "Rabia", "Encefalitis japonesa"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado",
        "riesgo_malaria": "Bajo (fronteras Birmania/Camboya)",
        "notas_salud": "Dengue presente todo el año. No tocar monos (rabia). Hospitales privados de alta calidad.",
        "notas_civicas": "No insultar a la familia real (lèse-majesté, pena de prisión). Cubrir hombros y rodillas en templos. Quitar zapatos al entrar.",
        "requisitos_especiales": [
            "Lèse-majesté: hablar de la monarquía con extrema precaución",
            "Drogas: pena de muerte por tráfico",
        ],
        "alertas_maec": [
            "Inestabilidad política recurrente",
            "Precaución con scams a turistas (gemas, taxis)",
            "Zona sur frontera con Malasia: presencia de grupos armados",
        ],
        "fuentes_prensa": [
            {"nombre": "Bangkok Post", "url": "https://www.bangkokpost.com/rss/data/topstories.xml", "idioma": "EN"},
            {"nombre": "The Nation Thailand", "url": "https://www.nationthailand.com/rss.xml", "idioma": "EN"},
            {"nombre": "Khaosod English", "url": "https://www.khaosodenglish.com/feed/", "idioma": "EN"},
        ],
    },

    "China": {
        "region": "Asia",
        "emoji": "🇨🇳",
        "capital": "Pekín",
        "moneda_nombre": "Yuan renminbi",
        "moneda_codigo": "CNY",
        "nivel_riesgo_maec": 2,
        "lat": 39.9042, "lon": 116.4074,
        "timezone": "Asia/Shanghai",
        "idioma": "Chino mandarín",
        "idioma_oficial": "Chino mandarín",
        "enchufes": "Tipo A / Tipo C / Tipo I",
        "voltaje": "220V",
        "frecuencia": "50Hz",
        "internet_calidad": "Restringida (GFW)",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "120 (ambulancia)",
        "telefono_policia": "110",
        "telefono_embajada_es": "+86 10 6532 3629",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/pekin/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida hasta 30 días (exención temporal 2024)",
        "pasaporte_o_dni": "Pasaporte",
        "vacunas_recomendadas": ["Hepatitis A", "Hepatitis B", "Encefalitis japonesa"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado",
        "riesgo_malaria": "Muy bajo",
        "notas_salud": "Contaminación atmosférica (PM2.5) en ciudades industriales. Llevar mascarilla en días de polución.",
        "notas_civicas": "Internet restringida (Google, WhatsApp, Instagram bloqueados — instalar VPN antes de llegar). No fotografiar instalaciones militares.",
        "requisitos_especiales": [
            "VPN necesaria — instalar ANTES de llegar (luego no se puede descargar)",
            "Apps de pago: WeChat Pay o Alipay necesarias (difícil sin número chino)",
            "Registro obligatorio en hoteles (lo hace el hotel)",
        ],
        "alertas_maec": [
            "Restricciones en internet — preparar VPN con antelación",
            "Legislación sobre fotografías y seguridad muy estricta",
            "Tensión en Xinjiang y Tibet — restricciones de acceso",
        ],
        "fuentes_prensa": [
            {"nombre": "South China Morning Post", "url": "https://www.scmp.com/rss/91/feed", "idioma": "EN"},
            {"nombre": "Global Times", "url": "https://www.globaltimes.cn/rss/outbrain.xml", "idioma": "EN"},
            {"nombre": "Caixin Global", "url": "https://www.caixinglobal.com/rss/latest_news.xml", "idioma": "EN"},
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # ÁFRICA
    # ══════════════════════════════════════════════════════════════════════════

    "Marruecos": {
        "region": "África",
        "emoji": "🇲🇦",
        "capital": "Rabat",
        "moneda_nombre": "Dírham marroquí",
        "moneda_codigo": "MAD",
        "nivel_riesgo_maec": 2,
        "lat": 33.9716, "lon": -6.8498,
        "timezone": "Africa/Casablanca",
        "idioma": "Árabe / Francés / Amazigh",
        "idioma_oficial": "Árabe, Amazigh",
        "enchufes": "Tipo C / Tipo E",
        "voltaje": "220V",
        "frecuencia": "50Hz",
        "internet_calidad": "Buena (ciudades)",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "190 (policía) / 150 (ambulancia)",
        "telefono_policia": "190",
        "telefono_embajada_es": "+212 5 37 63 39 00",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/rabat/es/Paginas/inicio.aspx",
        "visa_espana": "No requerida (hasta 90 días)",
        "pasaporte_o_dni": "Pasaporte o DNI",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea", "Rabia (zonas rurales)"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "No beber agua del grifo. Precaución con comida en puestos callejeros.",
        "notas_civicas": "Respetar Ramadán (no comer/beber en público). Vestimenta modesta en medinas. Regateo esperado en zoco.",
        "requisitos_especiales": [],
        "alertas_maec": [
            "Precaución en zonas fronterizas con Argelia (cerradas)",
            "Atención a falsas guías y estafas a turistas en medinas",
        ],
        "fuentes_prensa": [
            {"nombre": "Le360 Maroc", "url": "https://fr.le360.ma/rss.xml", "idioma": "FR"},
            {"nombre": "Yabiladi", "url": "https://www.yabiladi.com/rss/news.xml", "idioma": "FR"},
            {"nombre": "Hespress", "url": "https://www.hespress.com/feed", "idioma": "AR"},
        ],
    },

    "Egipto": {
        "region": "África",
        "emoji": "🇪🇬",
        "capital": "El Cairo",
        "moneda_nombre": "Libra egipcia",
        "moneda_codigo": "EGP",
        "nivel_riesgo_maec": 3,
        "lat": 30.0444, "lon": 31.2357,
        "timezone": "Africa/Cairo",
        "idioma": "Árabe",
        "idioma_oficial": "Árabe",
        "enchufes": "Tipo C / Tipo F",
        "voltaje": "220V",
        "frecuencia": "50Hz",
        "internet_calidad": "Moderada",
        "conduccion_lado": "Derecha",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "123 (ambulancia) / 122 (policía)",
        "telefono_policia": "122",
        "telefono_embajada_es": "+20 2 2735 6790",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/elcairo/es/Paginas/inicio.aspx",
        "visa_espana": "Requerida (e-Visa disponible)",
        "pasaporte_o_dni": "Pasaporte (6 meses mínimo)",
        "vacunas_recomendadas": ["Hepatitis A", "Tifoidea", "Hepatitis B"],
        "vacunas_obligatorias": [],
        "riesgo_salud": "Moderado",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "No beber agua del grifo. Precaución con diarrea del viajero. Calor extremo.",
        "notas_civicas": "Vestimenta modesta especialmente para mujeres. Regateo en mercados. Propinas (baksheesh) muy extendidas.",
        "requisitos_especiales": ["e-Visa obligatoria — tramitar en evisa.gov.eg"],
        "alertas_maec": [
            "Riesgo terrorista en el Sinaí Norte — zona no recomendada",
            "Frontera con Libia y Sudán — evitar",
            "Manifestaciones y disturbios ocasionales",
        ],
        "fuentes_prensa": [
            {"nombre": "Al-Ahram English", "url": "https://english.ahram.org.eg/RSSFeed.aspx", "idioma": "EN"},
            {"nombre": "Egypt Independent", "url": "https://egyptindependent.com/feed/", "idioma": "EN"},
            {"nombre": "Mada Masr", "url": "https://www.madamasr.com/en/feed/", "idioma": "EN"},
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # OCEANÍA
    # ══════════════════════════════════════════════════════════════════════════

    "Australia": {
        "region": "Oceanía",
        "emoji": "🇦🇺",
        "capital": "Canberra",
        "moneda_nombre": "Dólar australiano",
        "moneda_codigo": "AUD",
        "nivel_riesgo_maec": 1,
        "lat": -35.2809, "lon": 149.1300,
        "timezone": "Australia/Sydney",
        "idioma": "Inglés",
        "idioma_oficial": "Inglés (de facto)",
        "enchufes": "Tipo I",
        "voltaje": "230V",
        "frecuencia": "50Hz",
        "internet_calidad": "Muy buena",
        "conduccion_lado": "Izquierda",
        "distancia_sistema": "Métrico",
        "telefono_emergencias": "000",
        "telefono_policia": "000",
        "telefono_embajada_es": "+61 2 6273 3555",
        "url_maec": "https://www.exteriores.gob.es/Embajadas/canberra/es/Paginas/inicio.aspx",
        "visa_espana": "Requerida (eVisitor 651, gratuita online)",
        "pasaporte_o_dni": "Pasaporte (6 meses mínimo)",
        "vacunas_recomendadas": [],
        "vacunas_obligatorias": ["Fiebre amarilla si llega de zona endémica"],
        "riesgo_salud": "Muy bajo",
        "riesgo_malaria": "Ninguno",
        "notas_salud": "Sistema sanitario excelente. Protección solar imprescindible (índice UV muy alto). Peligro fauna silvestre.",
        "notas_civicas": "País muy seguro. Respeto estricto a la naturaleza. Fumar muy restringido. Multas por cruzar en rojo.",
        "requisitos_especiales": [
            "eVisitor obligatoria — tramitar en immi.homeaffairs.gov.au",
            "Declaración de bioseguridad muy estricta — no introducir alimentos",
        ],
        "alertas_maec": [
            "Fauna peligrosa (serpientes, medusas, cocodrilos en el norte)",
            "Temporada de incendios (nov-mar) en zonas rurales",
            "UV extremo — protección solar imprescindible",
        ],
        "fuentes_prensa": [
            {"nombre": "ABC News Australia", "url": "https://www.abc.net.au/news/feed/51120/rss.xml", "idioma": "EN"},
            {"nombre": "The Sydney Morning Herald", "url": "https://www.smh.com.au/rss/feed.xml", "idioma": "EN"},
            {"nombre": "The Guardian Australia", "url": "https://www.theguardian.com/australia-news/rss", "idioma": "EN"},
        ],
    },
}
