rss:
  - name: example_feed
    url: "https://news.un.org/feed/subscribe/en/news/all/rss.xml"
    enabled: true

  - name: un_global
    url: "https://news.un.org/feed/subscribe/en/news/all/rss.xml"
    enabled: true

  - name: reuters_world
    url: "http://feeds.reuters.com/Reuters/worldNews"
    enabled: true

  - name: euronews
    url: "https://www.euronews.com/rss?level=theme&name=news"
    enabled: true
